### ISSUE TITLE
Multiple crashes when trying to implement Bottom Bar Navigation

### ISSUE THREAD

**Issue by AhmedMourad0** [raamcosta/compose-destinations#113]
Hello there,

First of all, hats off for the amazing work being done on this library, such an improvement over the official way of doing navigation.

I've been trying to follow the [Tivi PR example](https://github.com/raamcosta/tivi/commit/5163492ce64d94e126d120a66e4f322854757c5e) to implement bottom bar navigation using nested graphs, but I ran into a few issues that are probably related to each other, I've prepared a sample app that showcases the errors:
https://github.com/AhmedMourad0/compose-destinations-crash
All the code mentioned here lives in the file [HomeScreen.kt](https://github.com/AhmedMourad0/compose-destinations-crash/blob/master/app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt)

The first one is this crash that happens when the app is launched:
`java.lang.RuntimeException: Unknown nav graph for destination home_screen`
to avoid the crash I had `NavDestination.navGraph()` in `HomeScreen.kt` return null if the destination is not found in any of the nested graphs and in that case the `selectedItem` is not updated.

If we avoid the first crash, we get a `StackOverflowError` that is caused by this bit in the `HomeScreen`
```Kotlin
DestinationsNavHost(
      navController = navController,
      navGraph = NavGraphs.root,
      modifier = Modifier
 )
```

and if we comment that out we get a third crash when trying to switch between the tabs
```
2022-04-27 00:31:28.390 4919-4919/dev.ahmedmourad.composedestinationscrash E/AndroidRuntime: FATAL EXCEPTION: main
    Process: dev.ahmedmourad.composedestinationscrash, PID: 4919
    java.lang.IllegalStateException: You must call setGraph() before calling getGraph()
        at androidx.navigation.NavController.getGraph(NavController.kt:94)
        at dev.ahmedmourad.composedestinationscrash.HomeScreenKt$HomeScreen$1$1$1.invoke(HomeScreen.kt:50)
        at dev.ahmedmourad.composedestinationscrash.HomeScreenKt$HomeScreen$1$1$1.invoke(HomeScreen.kt:46)
```

I'm probably missing something very obvious here but I ran out of ideas, any clues?
Thank you!

**Comment by raamcosta** [comment]
Hey @AhmedMourad0 !

Thanks for the kind words 🙏 

So, looking at your repository, I had some head scratching moments 😄 

First of all, you have on MainActivty a DestinationsNavHost that uses root nav graph, but then you use the same root nav graph inside HomeScreen. If you need multiple `DestinationsNavHost`, each should be using its own top-level navgraph (navgraphs without any parent, like the `@RootNavGraph` but you can create your own too).

But, I'm gonna assume you don't need multiple NavHosts. In this case, what exactly is your HomeScreen but a holder for all your other screens? Kind of like a NavHost, right? So I'd call it `AppNavigation` or `AppNavHost` or something like that instead of `HomeScreen`. Then you can just call it in MainActivity.

You then need a start for root nav graph. Since it will not contain any destination (it only contains nested nav graphs), you need to use one of those nested nav graphs as start.
After I did all that, the app is working 🎉 

I'll open a PR on your example to show you the changes I did. Let me know below if this solves it for you, or if there is any other issue!

**Comment by raamcosta** [comment]
Actually, I'll just put a patch here, it's easier than opening a PR xD

**Comment by raamcosta** [comment]
```
Index: app/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/build.gradle b/app/build.gradle
--- a/app/build.gradle	(revision 063b614837a9b38fc12a53c0379162ee71e9fcb7)
+++ b/app/build.gradle	(date 1651013190789)
@@ -66,8 +66,8 @@
     implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.4.1'
     implementation 'androidx.activity:activity-compose:1.4.0'
 
-    implementation 'io.github.raamcosta.compose-destinations:core:1.5.0-beta'
-    ksp 'io.github.raamcosta.compose-destinations:ksp:1.5.0-beta'
+    implementation 'io.github.raamcosta.compose-destinations:core:1.5.1-beta'
+    ksp 'io.github.raamcosta.compose-destinations:ksp:1.5.1-beta'
 
     testImplementation 'junit:junit:4.+'
     androidTestImplementation 'androidx.test.ext:junit:1.1.3'
Index: app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt
--- a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt	(revision 063b614837a9b38fc12a53c0379162ee71e9fcb7)
+++ b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt	(date 1651014065556)
@@ -5,10 +5,6 @@
 import androidx.activity.compose.setContent
 import androidx.compose.material.MaterialTheme
 import androidx.compose.material.Surface
-import androidx.compose.material.Text
-import androidx.compose.runtime.Composable
-import androidx.compose.ui.tooling.preview.Preview
-import com.ramcosta.composedestinations.DestinationsNavHost
 import dev.ahmedmourad.composedestinationscrash.ui.theme.ComposeDestinationsCrashTheme
 
 class MainActivity : ComponentActivity() {
@@ -18,7 +14,7 @@
             ComposeDestinationsCrashTheme {
                 // A surface container using the 'background' color from the theme
                 Surface(color = MaterialTheme.colors.background) {
-                    DestinationsNavHost(navGraph = NavGraphs.root)
+                    AppNavigation()
                 }
             }
         }
Index: app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt
--- a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt	(revision 063b614837a9b38fc12a53c0379162ee71e9fcb7)
+++ b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt	(date 1651014065552)
@@ -32,10 +32,8 @@
     Profile(NavGraphs.profile, Icons.Default.AccountCircle, "Profile")
 }
 
-@RootNavGraph(start = true)
-@Destination
 @Composable
-fun HomeScreen() {
+fun AppNavigation() {
     val navController = rememberNavController()
     Scaffold(
         bottomBar = {
Index: app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt
--- a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt	(revision 063b614837a9b38fc12a53c0379162ee71e9fcb7)
+++ b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt	(date 1651014065546)
@@ -4,7 +4,7 @@
 import com.ramcosta.composedestinations.annotation.RootNavGraph
 
 @NavGraph
-@RootNavGraph
+@RootNavGraph(start = true) // use start = true on whichever graph you want to start with
 annotation class DiscoverNavGraph(val start: Boolean = false)
 
 @NavGraph

```

**Comment by raamcosta** [comment]
I'll leave here another patch in case your simplified example did not need multiple NavHosts but your actual app actually does for some reason. 
In that case, i did this:

<details>
  <summary>⚠️ THE OTHER PATCH I POSTED IS LIKELY BETTER THAN THIS!!! ⚠️</summary>
  
```
Index: app/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/build.gradle b/app/build.gradle
--- a/app/build.gradle	(revision 063b614837a9b38fc12a53c0379162ee71e9fcb7)
+++ b/app/build.gradle	(date 1651014194516)
@@ -66,8 +66,8 @@
     implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.4.1'
     implementation 'androidx.activity:activity-compose:1.4.0'
 
-    implementation 'io.github.raamcosta.compose-destinations:core:1.5.0-beta'
-    ksp 'io.github.raamcosta.compose-destinations:ksp:1.5.0-beta'
+    implementation 'io.github.raamcosta.compose-destinations:core:1.5.1-beta'
+    ksp 'io.github.raamcosta.compose-destinations:ksp:1.5.1-beta'
 
     testImplementation 'junit:junit:4.+'
     androidTestImplementation 'androidx.test.ext:junit:1.1.3'
Index: app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt
--- a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt	(revision 063b614837a9b38fc12a53c0379162ee71e9fcb7)
+++ b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/MainActivity.kt	(date 1651014585781)
@@ -5,9 +5,6 @@
 import androidx.activity.compose.setContent
 import androidx.compose.material.MaterialTheme
 import androidx.compose.material.Surface
-import androidx.compose.material.Text
-import androidx.compose.runtime.Composable
-import androidx.compose.ui.tooling.preview.Preview
 import com.ramcosta.composedestinations.DestinationsNavHost
 import dev.ahmedmourad.composedestinationscrash.ui.theme.ComposeDestinationsCrashTheme
 
@@ -18,7 +15,7 @@
             ComposeDestinationsCrashTheme {
                 // A surface container using the 'background' color from the theme
                 Surface(color = MaterialTheme.colors.background) {
-                    DestinationsNavHost(navGraph = NavGraphs.root)
+                    DestinationsNavHost(navGraph = NavGraphs.home)
                 }
             }
         }
Index: app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt
--- a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt	(revision 063b614837a9b38fc12a53c0379162ee71e9fcb7)
+++ b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/HomeScreen.kt	(date 1651014741542)
@@ -32,7 +32,7 @@
     Profile(NavGraphs.profile, Icons.Default.AccountCircle, "Profile")
 }
 
-@RootNavGraph(start = true)
+@HomeNavGraph(start = true)
 @Destination
 @Composable
 fun HomeScreen() {
Index: app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt
--- a/app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt	(revision 063b614837a9b38fc12a53c0379162ee71e9fcb7)
+++ b/app/src/main/java/dev/ahmedmourad/composedestinationscrash/Graphs.kt	(date 1651014312347)
@@ -4,7 +4,10 @@
 import com.ramcosta.composedestinations.annotation.RootNavGraph
 
 @NavGraph
-@RootNavGraph
+annotation class HomeNavGraph(val start: Boolean = false)
+
+@NavGraph
+@RootNavGraph(start = true) // use start = true on whichever graph you want to start with
 annotation class DiscoverNavGraph(val start: Boolean = false)
 
 @NavGraph

```

</details>

**Comment by AhmedMourad0** [comment]
Thanks a lot!! there was definetly a lot of confusion going a round 😄 but now it works 🎉
