### ISSUE TITLE
Crash on screen rotation with a ModalBottomSheet opened

### ISSUE THREAD

**Issue by Leeonardoo** [raamcosta/compose-destinations#115]
When a ModalBottomSheet is opened and the screen is rotated, the app throws a IllegalArgumentException when using a ModalBottomSheetLayout (the one from accompanist).

Any ideas?

I have reproduced the same issue on the sample provided on this repo. Just go to the settings screen, click on Theme settings and rotate the device. The stack trace is as follows:

Also, I have tested it on a Android 12L emulator

```
15:16:22.828  E  FATAL EXCEPTION: main
                 Process: com.ramcosta.samples.destinationstodosample, PID: 7835
                 java.lang.IllegalArgumentException: The initial value must have an associated anchor.
                 	at androidx.compose.material.SwipeableState.ensureInit$material_release(Swipeable.kt:138)
                 	at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:594)
                 	at androidx.compose.material.SwipeableKt$swipeable$3.invoke(Swipeable.kt:573)
                 	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:263)
                 	at androidx.compose.ui.ComposedModifierKt$materialize$result$1.invoke(ComposedModifier.kt:258)
                 	at androidx.compose.ui.Modifier$Element$DefaultImpls.foldIn(Modifier.kt:107)
                 	at androidx.compose.ui.ComposedModifier.foldIn(ComposedModifier.kt:172)
                 	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
                 	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
                 	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
                 	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
                 	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
                 	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
                 	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
                 	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
                 	at androidx.compose.ui.CombinedModifier.foldIn(Modifier.kt:149)
                 	at androidx.compose.ui.ComposedModifierKt.materialize(ComposedModifier.kt:258)
                 	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke-Deg8D_g(Layout.kt:221)
                 	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Layout.kt:220)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:302)
                 	at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:255)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:252)
                 	at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:110)
                 	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1.invoke(ModalBottomSheet.kt:262)
                 	at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1.invoke(ModalBottomSheet.kt:247)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
                 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
                 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
                 	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
                 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
                 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
                 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
                 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
                 	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2547)
                 	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
                 	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
                 	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
                 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
15:16:22.828  E  	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
                 	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                 	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1209)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1219)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:892)
                 	at android.view.Choreographer.doFrame(Choreographer.java:820)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1194)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7844)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by raamcosta** [comment]
Yes, I believe this is a known issue with accompanist.

I remember seeing the issue on accompanist GitHub project.
I’ll look for it later and link it here.

**Comment by raamcosta** [comment]
https://github.com/google/accompanist/issues/910#issuecomment-1041872681

There seems to be a workaround of sorts, maybe you can try that and let me know if that works 🙏

**Comment by Leeonardoo** [comment]
I did a quick test and it unfortunately it seems like it didn't work. I'll dig more into it to see if I can find a workaround and I'll update here later

**Comment by Leeonardoo** [comment]
So, doing some more testing and a few debugging sessions, it actually seems that it's some issue with this library. Here's what I found:

1) Using the bottom sheet sample on Accompanist's repository, the error does not happen, because they made a workaround at SheetContentHost.

2) When trying to reproduce the same issue using only Compose Navigation I also couldn't get this error.

3) It only occurs when the screen is rotated while the bottom sheet is at HalfExpanded state, if it's fully expanded. That's because it tries to call newAnchors.getOffset with the current value (HalfExpanded) but only Hidden and Expanded are found inside the newAnchors map. here's a screenshot of that:

![Screen Shot 2022-04-29 at 13 20 15](https://user-images.githubusercontent.com/44948180/165984265-93f3031f-f2de-4038-b5d3-ee4370588997.png)

This is the exact line where the crash happens (line 139 of Swipeable.kt) on the sample provided in this repo

Any ideas about that @raamcosta ?

**Comment by raamcosta** [comment]
Hey @Leeonardoo !

thanks for taking the time to check on this, I really appreciate it 🙏

I’m still convinced Compose Destinations is not what’s causing this, as I’m just forwarding information to the accompanist APIs.
What I’m thinking now is that maybe it’s about the version of accompanist library?

I’ll check this later today hopefully and I will update this.

**Comment by raamcosta** [comment]
@Leeonardoo Sorry for not getting back to you yesterday, I did not have time to check this.

Today I have been trying stuff out and I found a minimal reproduction sample and it doesn't need my library. All we need is to use a Scaffold and have a very tall bottom sheet.
I took the code from the samples in the accompanist repo, slowly added things from my sample until I was able to reproduce it.

Here is the full sample code:

```kotlin
class BottomSheetNavSample : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            PlaygroundTheme { //TODO change with your theme name
                BottomSheetNavDemo()
            }
        }
    }
}

private object Destinations {
    const val Home = "HOME"
    const val Feed = "FEED"
    const val Sheet = "SHEET"
}

@OptIn(ExperimentalMaterialNavigationApi::class, ExperimentalAnimationApi::class)
@Composable
fun BottomSheetNavDemo() {
    val bottomSheetNavigator = rememberBottomSheetNavigator()
    val navController = rememberNavController(bottomSheetNavigator)

    ModalBottomSheetLayout(bottomSheetNavigator) {
        Scaffold {
            NavHost(
                navController = navController,
                startDestination = Destinations.Home
            ) {
                composable(Destinations.Home) {
                    HomeScreen(
                        showSheet = {
                            navController.navigate(Destinations.Sheet + "?arg=From Home Screen")
                        },
                        showFeed = { navController.navigate(Destinations.Feed) }
                    )
                }
                composable(Destinations.Feed) { Text("Feed!") }
                bottomSheet(Destinations.Sheet + "?arg={arg}") { backstackEntry ->
                    val arg = backstackEntry.arguments?.getString("arg") ?: "Missing argument :("
                    BottomSheet(
                        showFeed = { navController.navigate(Destinations.Feed) },
                        showAnotherSheet = {
                            navController.navigate(Destinations.Sheet + "?arg=${UUID.randomUUID()}")
                        },
                        arg = arg
                    )
                }
            }
        }
    }
}

@Composable
private fun HomeScreen(showSheet: () -> Unit, showFeed: () -> Unit) {
    Column(Modifier.fillMaxSize(), horizontalAlignment = Alignment.CenterHorizontally) {
        Text("Body")
        Button(onClick = showSheet) {
            Text("Show sheet!")
        }
        Button(onClick = showFeed) {
            Text("Navigate to Feed")
        }
    }
}

@Composable
private fun BottomSheet(showFeed: () -> Unit, showAnotherSheet: () -> Unit, arg: String) {
//    Box(
//        modifier = Modifier.height(400.dp) // !! ALSO makes it crash, or fillMaxHeight or fillMaxSize
//            .background(Color.Yellow)
//    ) {
        Column {
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Text("Sheet with arg: $arg")
            Button(onClick = showFeed) {
                Text("Click me to navigate!")
            }
            Button(onClick = showAnotherSheet) {
                Text("Click me to show another sheet!")
            }
        }
//    }

}
```

So I will open a new issue on the acompanist repo, maybe this is a new way to reproduce it that they haven't seen before.
Thanks again for reporting though, it was a good debugging process and I learnt something. I can change my sample so that it doesn't crash! If I used 300.dp height bottom sheet, then it doesn't crash (may depend on screen size I guess).

**Comment by Leeonardoo** [comment]
@raamcosta thanks for taking the time to investigate this further and creating the issue there! I hope they can figure it out 🎉
