### ISSUE TITLE
Generates default argument value as integer when type was declared as long

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#144]
After updating to v1.5.6, my app crashes on navigation attempt with the following stacktrace: 
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
        at com.ramcosta.composedestinations.navargs.primitives.DestinationsLongNavType.put(DestinationsLongNavType.kt:8)
        at androidx.navigation.NavArgument.putDefaultValue(NavArgument.kt:64)
        at androidx.navigation.NavDestination.addInDefaultArgs(NavDestination.kt:497)
        at androidx.navigation.NavController.navigate(NavController.kt:1655)
        at androidx.navigation.NavController.navigate(NavController.kt:1984)
        at androidx.navigation.NavController.navigate$default(NavController.kt:1979)
        at androidx.navigation.NavController.navigate(NavController.kt:1965)
        at com.ramcosta.composedestinations.navigation.DestinationsNavController.navigate(DestinationsNavController.kt:27)
        at com.ramcosta.composedestinations.navigation.DestinationsNavigator$DefaultImpls.navigate(DestinationsNavigator.kt:40)
        at com.ramcosta.composedestinations.navigation.DestinationsNavController.navigate(DestinationsNavController.kt:13)
        at com.ramcosta.composedestinations.navigation.DestinationsNavigator$DefaultImpls.navigate$default(DestinationsNavigator.kt:35)
        // bunch of junk
```

Digging into the  generated sources resulted for me in finding this:

Parent destination:
```

@Composable
@Destination
@RootNavGraph(start = true)
fun HomeScreen(
    navigator: DestinationsNavigator,
) = MVIComposable(getViewModel<HomeViewModel>()) { state -> 
// ...
```
And destination screen:
```

@Composable
@Destination(style = DestinationStyle.BottomSheet::class)
fun EditRitualScreen(
    ritualId: Long = 0,
    navigator: DestinationsNavigator,
 // ... 
```

The generated code is as follows:
```
object EditRitualScreenDestination : TypedDestination<EditRitualScreenDestination.NavArgs> {
    
    override fun invoke(navArgs: NavArgs): Direction = with(navArgs) {
        invoke(ritualId)
    }
     
    operator fun invoke(
		ritualId: Long = 0,
    ): Direction {
        return object : Direction {
            override val route = "$baseRoute" + 
					"?ritualId=${DestinationsLongNavType.serializeValue(ritualId)}"
        }
    }
    
    @get:RestrictTo(RestrictTo.Scope.SUBCLASSES)
    override val baseRoute = "edit_ritual_screen"

    override val route = "$baseRoute?ritualId={ritualId}"
    
	override val arguments get() = listOf(
		navArgument("ritualId") {
			type = DestinationsLongNavType
			defaultValue = 0
		}
	)

	override val style = DestinationStyle.BottomSheet

    /* ... */

	data class NavArgs(
		val ritualId: Long = 0,
	)
}
```
The "navArgument() { defaultValue = 0 }" is what I'm inclined to blame as the cause. It seems you accidentally put an integer value as defaultValue and then try to parse it as Long.

**Comment by raamcosta** [comment]
Hey @Nek-12 !

I see! I wonder how this did not happen on older version though 🤔 
You are right, `defaultValue = 0` is gonna consider this as an Int. 

Well, it's an easy fix, so I'll do a quick release with it :)

**Comment by Nek-12** [comment]
I'm not sure either, although I jumped from 1.3.x to 1.5.6, couldn't really keep track.

**Comment by raamcosta** [comment]
Done! You can update to 1.5.7-beta and this will be fixed :)
