### ISSUE TITLE
Crash on Deeplink

### ISSUE THREAD

**Issue by polivmi1** [raamcosta/compose-destinations#147]
When moving from 1.4.4 to 1.5.x I am seeing this crash when opening a pending intent and handling that with Deeplink:

```
java.lang.IllegalStateException: Calling multiple DestinationsNavHost with a navigation graph containing the same route ('root')
        at com.ramcosta.composedestinations.utils.NavGraphRegistry.checkUniqueness(NavGraphSpecHolder.kt:31)
        at com.ramcosta.composedestinations.DestinationsNavHostKt$HandleNavGraphRegistry$1.invoke(DestinationsNavHost.kt:99)
        at com.ramcosta.composedestinations.DestinationsNavHostKt$HandleNavGraphRegistry$1.invoke(DestinationsNavHost.kt:98)
        at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
        at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1006)
        at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:774)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:794)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:827)
        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3705)
        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3705)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:508)
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:468)
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:441)
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:432)
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:421)
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:732)
        at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1.invoke-0kLqBqw(BoxWithConstraints.kt:69)
        at androidx.compose.foundation.layout.BoxWithConstraintsKt$BoxWithConstraints$1$1.invoke(BoxWithConstraints.kt:67)
        at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:590)
        at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:44)
        at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:658)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
        at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1420)
        at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1419)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2098)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:112)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
        at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui_release(LayoutNode.kt:1419)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:75)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1358)
        at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:135)
        at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:44)
        at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:658)
        at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
        at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1420)
        at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1419)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2098)
```

Single activity with
android:launchMode="singleTop"

DestinationsNavHost gets recomposed when opening the deeplink, which causes the crash. Any hint on how to avoid it or is there a bug in the library of not clearing the previous DestinationsNavHost in this case?

**Comment by raamcosta** [comment]
Hi @polivmi1 !

We do have code to clear it and we also take decomposition into account but I’m guessing there is some hole in the logic if you’re seeing this but you don’t have multiple nav hosts for the same nav graph. 

So I’ll be checking this out later today and hopefully make a release with the fix. Thank you for reporting! 🙏

**Comment by polivmi1** [comment]
Thank you very much for always being so responsive and quick! If you will have problems reproducing or fixing it, I could create a sample project.

**Comment by raamcosta** [comment]
I mean if you could do that I would really appreciate it 🙏
That will probably save me some precious time which I don’t have much of these days 😅

**Comment by polivmi1** [comment]
In the playground change this code in MainActivity and then click the notification

```

class MainActivity : ComponentActivity() {

    private val dependencyContainer = DependencyContainer()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            CompositionLocalProvider(LocalDependencyContainer provides dependencyContainer) {
                PlaygroundApp()
            }
        }
        var pendingIntent: PendingIntent? = null
        pendingIntent = TaskStackBuilder.create(applicationContext).run {
            addNextIntentWithParentStack(
                Intent(
                    Intent.ACTION_VIEW,
                    "https://destinationssample.com/profile/id".toUri(),
                    applicationContext,
                    MainActivity::class.java
                )
            )
            getPendingIntent(0, PendingIntent.FLAG_IMMUTABLE)!!
        }
        displayNotification(
            "title",
            "message",
            100,
            "DEFAULT", pendingIntent
        )
    }


    private fun displayNotification(
        title: String,
        text: String,
        notificationID: Int,
        channel: String,
        pendingIntent: PendingIntent?
    ) {
        val notificationManager = applicationContext
            .getSystemService(NOTIFICATION_SERVICE) as NotificationManager
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val defaultChannel =
                NotificationChannel(
                    "DEFAULT",
                    "DEFAULT",
                    NotificationManager.IMPORTANCE_DEFAULT
                )
            defaultChannel.lockscreenVisibility = Notification.VISIBILITY_PUBLIC
            notificationManager.createNotificationChannel(defaultChannel)
        }
        val builder = NotificationCompat.Builder(
            applicationContext,
            channel
        )
        builder.setContentTitle(title)
        builder.setTicker(title)
        builder.setContentText(text)
        builder.setSmallIcon(R.drawable.ic_launcher_background)

        builder.setDefaults(NotificationCompat.DEFAULT_LIGHTS or NotificationCompat.DEFAULT_VIBRATE)
        val notificationIntent = Intent(applicationContext, MainActivity::class.java)
        builder.setContentIntent(
            pendingIntent ?: PendingIntent.getActivity(
                applicationContext,
                0,
                notificationIntent,
                0
            )
        )
        val notification = builder.build()

        //Dismiss the notification on tap
        notification.flags = notification.flags or Notification.FLAG_AUTO_CANCEL

        //Update the proper notification
        notificationManager.notify(notificationID, notification)
    }
}
```

**Comment by raamcosta** [comment]
@polivmi1 please try 1.5.8-beta and let me know if all works for you now 🙂 

Sorry for the inconvenience! And thank you for reporting 🙏

**Comment by raamcosta** [comment]
Maven is being super slow for some reason 1.5.8-beta is still not available 😕 
I'll update this when it becomes available

**Comment by polivmi1** [comment]
Now available and it looks good. I will let you know if we encounter more problems. Thank you for the swift fix!

**Comment by raamcosta** [comment]
Yeah I had to open issue on sonatype jira 😅

Nice, let me know 🙂

**Comment by polivmi1** [comment]
@raamcosta so this is happening in production too. I will most likely downgrade to 1.4.4. I am not able to reproduce it yet, but it seems like it happens during normal navigation from screen to screen after a few ms. 1 screen was opened successfully, but the next screen (the same way to open it) crashed. This must be some recomposition in a case that isn't handled and race condition happens crashing it sometimes. The rate how many times it crashed is quite low.

```
Fatal Exception: java.lang.IllegalStateException: Calling multiple DestinationsNavHost with a navigation graph containing the same route ('root')
       at com.ramcosta.composedestinations.utils.NavGraphRegistry$UniqueRouteCheckRunnable.run(NavGraphSpecHolder.kt:68)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by polivmi1** [comment]
This is unrelated to the crash, but a stack trace of what is called when that screen is opened. That might be helpful for investigating what is happening.
The composable(screen) is called after the stack trace.
```
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:116)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:34)
com.ramcosta.composedestinations.manualcomposablecalls.DestinationLambda$Normal.invoke (DestinationLambda.kt:28)
com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.CallComposable (AnimatedNavHostEngine.kt:289)
com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.access$CallComposable (AnimatedNavHostEngine.kt:58)
com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addAnimatedComposable$1$5.invoke (AnimatedNavHostEngine.kt:206)
com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addAnimatedComposable$1$5.invoke (AnimatedNavHostEngine.kt:202)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:135)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:34)
com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9$1.invoke (AnimatedNavHost.kt:212)
com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9$1.invoke (AnimatedNavHost.kt:210)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:107)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:34)
androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:228)
androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider (SaveableStateHolder.kt:84)
androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider (NavBackStackEntryProvider.kt:60)
androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider (NavBackStackEntryProvider.kt:1)
androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:52)
androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke (NavBackStackEntryProvider.kt:51)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:107)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:34)
androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt:228)
androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider (NavBackStackEntryProvider.kt:47)
com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9.invoke (AnimatedNavHost.kt:210)
com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9.invoke (AnimatedNavHost.kt:202)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:135)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:34)
androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke (AnimatedContent.kt:658)
androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke (AnimatedContent.kt:648)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:116)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:34)
androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl (AnimatedVisibility.kt:937)
androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility (AnimatedVisibility.kt:606)
androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke (AnimatedContent.kt:638)
androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke (AnimatedContent.kt:625)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:107)
androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt:34)
androidx.compose.animation.AnimatedContentKt.AnimatedContent (AnimatedContent.kt:671)
com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost (AnimatedNavHost.kt:197)
com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost (AnimatedNavHost.kt:91)
com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.NavHost (AnimatedNavHostEngine.kt:83)
com.ramcosta.composedestinations.DestinationsNavHostKt.DestinationsNavHost (DestinationsNavHost.kt:71)
```

**Comment by raamcosta** [comment]
Thanks for letting me know @polivmi1 !

I believe I found a better solution to the problem. This way I don't even need to restrict the "one NavHost = one Top level route". So you won't be seeing this crash anymore :) 

Thanks for staying with me and helping me improve the lib! 🙏 
I'll comment here once I release this fix.

**Comment by raamcosta** [comment]
1.5.9-beta released! 

Thank you again 🙂

**Comment by polivmi1** [comment]
That was quick! Thank you! I will let you know if we find something else.
