### ISSUE TITLE
Deeplinks and BuildConfig, code not generated

### ISSUE THREAD

**Issue by JustJerem** [raamcosta/compose-destinations#178]
Hello Rafael,
First of all, I would like to thank you for this great bookstore. A real pleasure to use every day ! 👏

My issue is that I trying to use DeepLinks with a changing configuration, thanks to BuildConfig.
The application compiles, but it crashes when launching on the phone with this error:

`    java.lang.IllegalStateException: The NavDeepLink must have an uri, action, and/or mimeType.`

And indeed, looking in the generated code, nothing appears in the Deeplinks variable.

```
override val deepLinks get() = listOf(
	navDeepLink {
	}
)
```

This works perfectly if I hardcode the URL in the right field, but when I pass it in the BuildConfig, it doesn't generate. And I need it because our application has 4 environments.

**Current state :**

_DashboardScreen.kt_
```
const val DEEPLINK_DASHBOARD_URI = "https://website.com/dashboard"
@Destination(deepLinks = [
    DeepLink(action = DEEPLINK_DASHBOARD_URI)
])
@Composable
fun DashboardScreen(
    viewModel: DashboardViewModel = hiltViewModel(),
    navigator: DestinationsNavigator,
) {
```

**What I try to achieve :**

_build.gradle_
```
buildConfigField "String", "DEEPLINK_DASHBOARD_URI", "\"https://website.com/dashboard\""
```

_DashboardScreen.kt_
```
@Destination(deepLinks = [
    DeepLink(action = BuildConfig.DEEPLINK_DASHBOARD_URI)
])
@Composable
fun DashboardScreen(
    viewModel: DashboardViewModel = hiltViewModel(),
    navigator: DestinationsNavigator,
) {
```

Is there a solution ?
Sorry if I missed something in the documentation.

**Comment by Miiel** [comment]
Hiya! 
@raamcosta Can you show us an example please? I don't quite understand what you mean.

I have an app with multiple build flavors, and the scheme for the deeplinks is based on the build.FLAVOR. 

I wrote this code based on your answer. Works for a little bit, until I open a notification with a deeplink. Then it throws the following exception:

>      java.lang.IllegalArgumentException: Registering multiple navigation graphs with same route ('newRoot') is not allowed.


```
        const val TRANSIT_ALARM_DEEPLINK_URL = "${BuildConfig.FLAVOR}://transitalarm"
        const val ALERT_DEEPLINK_URL = "${BuildConfig.FLAVOR}://alert/{alertId}"
        private var navGraph: NavGraph? = null


 internal fun regenerateRootNavGraph(): NavGraph {
        if (navGraph == null) {
            val newRoot = NavGraphs.root.copy(route = "newRoot")

            val destinations = newRoot.destinations.toMutableList()
            destinations.remove(SingleAlertDetailScreenDestination)
            destinations.remove(HeadlineDetailsDestination)

            SingleAlertDetailScreenDestination.withDeepLink {
                uriPattern = ALERT_DEEPLINK_URL
            }.routedIn(newRoot)

            HeadlineDetailsDestination.withDeepLink {
                uriPattern = TRANSIT_ALARM_DEEPLINK_URL
            }.routedIn(newRoot)

            navGraph = newRoot.copy(destinations = destinations)
        }
        return navGraph!!
    }
```

**Comment by cvb941** [comment]
Hi, you can try adding the code below to your build.gradle, it should make the BuildConfig class available to KSP.
```
ksp {
    allowSourcesFromOtherPlugins = true
}
```

**Comment by ryanholden8** [comment]
> Hi, you can try adding the code below to your build.gradle, it should make the BuildConfig class available to KSP.
> 
> ```
> ksp {
>     allowSourcesFromOtherPlugins = true
> }
> ```

I get this build error when using this option:

```
Circular dependency between the following tasks:
:app:kaptDebugKotlin
\--- :app:kaptGenerateStubsDebugKotlin
     \--- :app:kspDebugKotlin
          \--- :app:kaptDebugKotlin (*)
```

@cvb941 - Where you able to get it working? If so, mind sharing a few snippets of the code?

**Comment by cvb941** [comment]
Sorry, I just enabled that option and it worked, nothing special. I am not using kapt though.

**Comment by Miiel** [comment]
@ryanholden8 Did you find a solution or maybe a workaround? I think my project requires kapt for Hilt, and ksp for destinations. I also need to set ksp. allowSourcesFromOtherPlugins to true because we have build flavors and we need deeplinks based on build flavors.

I feel like there must be a way to have ksp_gradleTask.dependsOn(BuildConfig_gradleTask), but I'm not very familiar with ksp and gradle.

**Comment by ryanholden8** [comment]
@Miiel - We did not, we duplicated the references. Not ideal but not much of a choice.

**Comment by javierpe** [comment]
@raamcosta I have many issues with this in CI/CD. Did you solve it?

**Comment by ninovanhooff** [comment]
The way I solved this was to register a single pattern as documented, using an app scheme, for example:

Screen @Destination annotation
```
deepLinks = [
        DeepLink(
            uriPattern = "myapp://groups/join?token={token}",
        ),
    ]
```

Then, in the MainActivity, I used traditional url- handling to transform environment (prod, dev, acc) specific https urls in to the registered myapp:// pattern and feed that into the navigator

MainActivity kotlin:

```
 override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        this.intent = intent
        deeplinkManager.onNewIntent(intent)
    }
```

DeeplinkManager
```
@Singleton
class DeeplinkManager @Inject constructor(
    private val deeplinkParser: DeeplinkParser,
) {

    private val _deeplinkFlow = MutableStateFlow(Uri.EMPTY)
    val deeplinkFlow: Flow<Uri> = _deeplinkFlow

    fun onNewIntent(intent: Intent?) {
        Napier.d {
            "onNewIntent received with data ${intent?.data} and extras ${
                intent?.extras?.keySet()?.toList()
            }"
        }
        if (intent == null) return

        deeplinkParser.parseIntent(intent)?.let {
            _deeplinkFlow.value = it
        }
    }

    fun onDeeplinkHandled() {
        _deeplinkFlow.value = Uri.EMPTY
    }
}
```

DeeplinkParser: A class transforming `https://<dev | acc | prod>.mycompany.com/join?token=ABCDEF` to `myapp://join/token={token}`



MainActivity composable content:

```
val navController = rememberAnimatedNavController()
DeeplinkHandler(navController)
```

DeeplinkHandler
```
@Composable
    private fun DeeplinkHandler(navController: NavHostController) {
        val deeplink by deeplinkManager.deeplinkFlow.collectAsStateWithLifecycle(
            initialValue = Uri.EMPTY
        )

        if (deeplink != Uri.EMPTY) {
            Napier.d { "Navigating to deeplink $deeplink" }
            navController.navigate(deeplink)
            deeplinkManager.onDeeplinkHandled()
        }
    }
 ```

**Comment by amaranthius** [comment]
A bit late to the party, but just wanted to share a workaround that worked for me. Might be helpful to some folks out there. 

I've basically used this suggestion:

> ```
> ksp {
>     allowSourcesFromOtherPlugins = true
> }
> ```

but with this extra step:
```
tasks.withType<com.google.devtools.ksp.gradle.KspTaskJvm> {
    mustRunAfter("generateDebugBuildConfig")
}
```

This little block makes sure that `BuildConfig` would've been generated by the time KSP starts to do its thing. Bear in mind that, depending on your particular case, there might be more tasks that need to be added to `mustRunAfter`.

Of course, having an elegant out-of-the-box solution would be way better, but this is not too ugly for a workaround. Hope. this helps!

**Comment by pm-nchain** [comment]
@raamcosta is it possible to improve error message in this situation? Error like following is kind of misleading.

```
 java.lang.IllegalArgumentException: Deep link null can't be used to open destination Destination(0xa4735ba4) route=verify_email_username/{email}/{code}.
 Following required arguments are missing: [email, code]
 	at androidx.navigation.NavDestination.addDeepLink(NavDestination.kt:355)
 	at androidx.navigation.compose.NavGraphBuilderKt.composable(NavGraphBuilder.kt:104)
 	at androidx.navigation.compose.NavGraphBuilderKt.composable$default(NavGraphBuilder.kt:78)
 	at com.ramcosta.composedestinations.spec.DestinationStyleKt.addActivityDestination(DestinationStyle.kt:158)
 	at com.ramcosta.composedestinations.DefaultNavHostEngine.composable(DefaultNavHostEngine.kt:123)
 	at com.ramcosta.composedestinations.DestinationsNavHostKt.addNavGraphDestinations(DestinationsNavHost.kt:115)
 	at com.ramcosta.composedestinations.DestinationsNavHostKt.access$addNavGraphDestinations(DestinationsNavHost.kt:1)
 	at com.ramcosta.composedestinations.DestinationsNavHostKt$addNestedNavGraphs$1$1$1.invoke(DestinationsNavHost.kt:142)
 	at com.ramcosta.composedestinations.DestinationsNavHostKt$addNestedNavGraphs$1$1$1.invoke(DestinationsNavHost.kt:141)
```

**Comment by raamcosta** [comment]
Does anyone know if this is still the case?

**Comment by amaranthius** [comment]
> Does anyone know if this is still the case?

Is it supposed to be working? Haven't tried since I've put in place the workaround I've mentioned earlier

**Comment by lucanicoletti** [comment]
It is still the case, facing this
