### ISSUE TITLE
Calling multiple DestinationsNavHost with a navigation graph containing the same route ('root')

### ISSUE THREAD

**Issue by yadavraju** [raamcosta/compose-destinations#181]
I am having issues, I have startactivity that have original navhost that have some compose screen after completing some step I am going to Mainactivity that have your compose destination with multiple jetpack screen (up to this one working fine). from one jetpack screen I log out I have to go back to startactivity that is also working but if want to navigate to Mainactivity again that I am getting that crash. How should I handle that? Please help  
  
  java.lang.IllegalStateException: Calling multiple DestinationsNavHost with a navigation graph containing the same route ('root')
        at sx2$a.run(SourceFile:68)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by yadavraju** [comment]
@raamcosta please have

**Comment by raamcosta** [comment]
What version are you using?

**Comment by yadavraju** [comment]
I am using 1.5.8-beta

**Comment by raamcosta** [comment]
Update to 1.5.13 🙂

**Comment by yadavraju** [comment]
@raamcosta Thank you so much for helping. It looks like it's working for the 1st time. 

could you please explain to me what was issue in the library was causing that issue? I really want to understand navigation in jetpack in general

**Comment by raamcosta** [comment]
It was a bug with old version. We tried to limit the top level NavGraphs one per NavHost call. But sometimes the Android framework would call the same NavHost multiple times (besides composition) so we drop that validation at runtime.

you should still only use each top level nav graph on one only DestinationsNavHost call
