### ISSUE TITLE
NavController#isRouteOnBackStack returns false

### ISSUE THREAD

**Issue by TemMax** [raamcosta/compose-destinations#191]
Hello. I tried to add bottom navigation to my project using your sample project as an example.
But for a strange reason, NavController#isRouteOnBackStack returns false and this leads to an issue with the bottom navigation selected state and popping to the root screen when the bottom navigation tab is reselected. I researched this problem but checked everything and tried to change my code to 1:1 as in your sample. But your sample works, my project — no.

**Comment by raamcosta** [comment]
Hey 👋 

If isRouteOnBackStack returns false, it means it is not on the back stack.
I used that strategy to know if a tab is selected or not but depending on the app (more frequently than not actually, maybe I have to change the sample code 🤔) you’ll want each tab to be corresponding to a nested nav graph. 
Then instead of checking if some screen is on back stack you can check if the current visible screen belongs to the nav graph of each tab.

You can find tons of examples out there doing it this way for official compose navigation (now in Android Google’s repository for example). Same code will work for compose destinations. Just remember that each NavGraph and each destination generated have a “route” field you can use to access the string route 🙂

Ill trey to change the sample soon though.
Let me know if this helped!

**Comment by TemMax** [comment]
I see, thanks. But one more question. In this case I have screens that could be opened in different NavGraphs. For example some "DetailsScreen" that could be opened from the "A" graph and "B" and "C" graph.
Is it could be achieved?

**Comment by raamcosta** [comment]
Of course :) you can navigate everywhere.
I hope you mean nested nav graphs though. If you mean multiple top level Nav graphs and multiple NavHosts then you need to do some more work to pass the nav controllers around.

**Comment by TemMax** [comment]
I can't understand how to write a Destination that could be opened from different NavGraphs

**Comment by TemMax** [comment]
I created some nested NavGraphs, but got this error when tried to rebuild the project:

```
e: [ksp] java.lang.NullPointerException
	at com.ramcosta.composedestinations.codegen.writers.sub.NavGraphsSingleObjectWriter.write(NavGraphsSingleObjectWriter.kt:65)
	at com.ramcosta.composedestinations.codegen.writers.ModuleOutputWriter.write(ModuleOutputWriter.kt:39)
	at com.ramcosta.composedestinations.codegen.CodeGenerator.generate(CodeGenerator.kt:44)
	at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:48)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:237)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:235)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:330)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:235)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:264)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:255)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:157)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:94)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1642)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by raamcosta** [comment]
Like any other destination. Just annotate it with Destination and whatever NavGraph it’s supposed to belong to.

**Comment by raamcosta** [comment]
What version of the lib are you using?

**Comment by TemMax** [comment]
Version: 1.5.13-beta

**Comment by raamcosta** [comment]
Let me check that stack trace

**Comment by TemMax** [comment]
Ok, thanks

**Comment by TemMax** [comment]
Some additional info:
Kotlin version: 1.7.0
KSP version: 1.7.0-1.0.6
Compose compiler version: 1.2.0
Compose libs versions: 1.1.1

**Comment by raamcosta** [comment]
Ok yeah this error happens if you have some declaration of a NavGraph that is not being used by any Destination.

I definitely need to fix this, so thank you so much for letting me know 🙏

Until then, comment out the NavGraph annotations that you’re not using.

**Comment by TemMax** [comment]
Now it works, thanks a lot.

Could you please provide a little example of code on how to check if the current visible screen belongs to the nav graph of each tab?

**Comment by raamcosta** [comment]
You get the current screen Destination in the same way as the sample.
Then you can use YourNavGraph.allDestinations.contains(current) for example. (I’m not in the PC sorry if it’s not exactly like this 😅)

**Comment by TemMax** [comment]
Not sure about how to get current screen Destination. Example uses navController#isRouteOnBackStack function

**Comment by TemMax** [comment]
Oh sorry. I found :)

**Comment by raamcosta** [comment]
https://github.com/raamcosta/compose-destinations/blob/main/sample/src/main/java/com/ramcosta/destinations/sample/ui/composables/SampleScaffold.kt

We use it here, sorry

**Comment by TemMax** [comment]
But there is appears one more problem.
Example: We have "DetailsScreen" which could be opened from "Home" tab (HomeNavGraph) and "Favorites" tab (FavoritesNavGraph). DetailsScreen has @RootNavGraph annotation. Then when we opened DetailsScreen from any tab (Home or Favorites) — no one of them will be selected.

**Comment by raamcosta** [comment]
This is where I’d say that you need to think how you’ll structure your nav graphs and how you’ll do the logic of “is bottom item selected”.
There are tons of ways to achieve this, even with official compose navigation you would have this exact same problem to solve 🙂

One way here is you put detail screen in both nav graphs. For that you need to create two Composables, annotate they with Destination and both of them call the same Composable for the actual UI building.

**Comment by TemMax** [comment]
Sorry for a lot of questions. One more :)
Is it possible to do something like: First graph only for tabs (A, B, C) and Second graph like "FullScreen" graph, the screens of which will open on top of the bottom navigation?

**Comment by raamcosta** [comment]
I don’t know exactly what you mean with on top of bottom navigation.

you can see in my sample that my login page doesn’t have bottom and top bars and the others do. Is that what you want?

**Comment by TemMax** [comment]
Not at all. I meant that the screens open on top of the screen with tabs.

**Comment by raamcosta** [comment]
What does it mean “on top”? Like a bottom sheet or a dialog? Can you see the screens with tabs below in some way?

**Comment by TemMax** [comment]
I found an example:

https://user-images.githubusercontent.com/17501751/180655697-ce85811b-cdd0-42ff-9ebc-3335d7b3cba4.mp4

**Comment by raamcosta** [comment]
That’s just an animation of the screen coming in.
It’s the same as what I have on login, just with a different animation. Right? 

So in the sample I’d you logout, I’m hiding the top and bottom bars with its own animation.
You can remove that animation and add animation to the screen coming in and the screen going out. That’s it 🙂

**Comment by TemMax** [comment]
Ohh, sorry, and thanks a lot. I chose your first variant with different destinations for tabs.
But now I see that when I switch between tabs the screens don't save their state. 
Here is the code:
![image](https://user-images.githubusercontent.com/17501751/180658375-b3654df4-a576-4044-978b-cdf0114886de.png)

**Comment by raamcosta** [comment]
This is a multi-step thing 😅 

I cannot help you at the moment, but I'm sure you can find examples of doing this with official lib, which you can easily adapt to Compose Destinations.

**Comment by TemMax** [comment]
Ok. Thanks a lot!
