### ISSUE TITLE
There is no NavGraphs

### ISSUE THREAD

**Issue by hoomanhooshyar** [raamcosta/compose-destinations#200]
When I want to add my root, Kotlin can't find any NavGraphs and the Destination classes don't add to my project after rebuild the project.

This is my build file in project level:

```
buildscript {
    ext {
        compose_version = '1.2.0-rc03'
    }
    dependencies {
        classpath "com.google.dagger:hilt-android-gradle-plugin:2.40.5"
        classpath "com.android.tools.build:gradle:7.0.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31"
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '7.1.0' apply false
    id 'com.android.library' version '7.1.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.10' apply false

}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

This is my dependencies:

```
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'com.google.devtools.ksp' version '1.6.10-1.0.2'
}
    // Compose Nav Destinations
    implementation 'io.github.raamcosta.compose-destinations:core:1.7.15-beta'
    ksp 'io.github.raamcosta.compose-destinations:ksp:1.7.15-beta'
```

And this is my root page annotation and other page annotation:

```
//Main page
@RootNavGraph(start = true)
@Destination
@Composable

//Second page


@Composable
@Destination
```

But this is the Error that android studio shows me in this line:

`DestinationsNavHost(navGraph = NavGraphs.root)`

Unresolved reference: NavGraphs

I can't import the library above the class
Why?
I uploaded the line that has an Error

![Capture](https://user-images.githubusercontent.com/47898766/182200674-f2d7aac0-8342-4e50-8b4f-40a9ca198536.PNG)

Where did I make a mistake?

**Comment by linean** [comment]
Maybe you forgot to add source set with KSP files? Checkout step 3 in the readme: https://github.com/raamcosta/compose-destinations#3-and-finally-you-need-to-make-sure-the-ide-looks-at-the-generated-folder

**Comment by hoomanhooshyar** [comment]
Yes, I forgot to add those line.
But after add those line, I got new Error. Of course I know this Error is not related to the new lines but I can't fix that.

This is the Error:
```
java.lang.NoSuchMethodError: 'kotlin.sequences.Sequence com.google.devtools.ksp.processing.Resolver.getSymbolsWithAnnotation$default(com.google.devtools.ksp.processing.Resolver, java.lang.String, boolean, int, java.lang.Object)'
	at com.ramcosta.composedestinations.ksp.processors.Processor.getComposableDestinations(Processor.kt:54)
	at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:25)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:195)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:193)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:287)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:193)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I add my build file's lines:

Build Project level:

```
buildscript {
    ext {
        compose_version = '1.1.0'
    }
    dependencies {
        classpath "com.google.dagger:hilt-android-gradle-plugin:2.40.5"
        classpath 'com.android.tools.build:gradle:7.2.1'
        //classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '7.2.1' apply false
    id 'com.android.library' version '7.2.1' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.10' apply false

}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
Build Module level:

```
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'com.google.devtools.ksp' version '1.6.10-1.0.2'
}

kotlin{
    sourceSets{
        debug{
            kotlin.srcDir("build/generated/ksp/debug/kotlin")
        }
        release{
            kotlin.srcDir("build/generated/ksp/release/kotlin")
        }
    }
}

android {
    compileSdk 32

    defaultConfig {
        applicationId "com.application.meshe"
        minSdk 24
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        //coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion compose_version
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.8.0'
    implementation "androidx.compose.ui:ui:$compose_version"
    implementation "androidx.compose.material:material:$compose_version"
    implementation "androidx.compose.ui:ui-tooling-preview:$compose_version"
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.3.1'
    implementation 'androidx.activity:activity-compose:1.3.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:$compose_version"
    debugImplementation "androidx.compose.ui:ui-tooling:$compose_version"
    debugImplementation "androidx.compose.ui:ui-test-manifest:$compose_version"

    //Dagger - Hilt
    implementation "com.google.dagger:hilt-android:2.40.5"
    kapt "com.google.dagger:hilt-android-compiler:2.40.5"
    implementation "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha03"
    kapt "androidx.hilt:hilt-compiler:1.0.0"
    implementation 'androidx.hilt:hilt-navigation-compose:1.0.0'

    // Room
    implementation "androidx.room:room-runtime:2.4.2"
    kapt "androidx.room:room-compiler:2.4.2"

    // Kotlin Extensions and Coroutines support for Room
    implementation "androidx.room:room-ktx:2.4.2"

    // Compose Nav Destinations
    implementation 'io.github.raamcosta.compose-destinations:core:1.7.15-beta' //1.1.2-beta
    ksp 'io.github.raamcosta.compose-destinations:ksp:1.7.15-beta'

    // Compose dependencies
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.4.1"
    implementation "androidx.compose.material:material-icons-extended:$compose_version"
    implementation "com.google.accompanist:accompanist-flowlayout:0.17.0"
    implementation 'androidx.paging:paging-compose:1.0.0-alpha14'
    implementation "androidx.activity:activity-compose:1.6.0-alpha01"
    implementation "com.google.accompanist:accompanist-swiperefresh:0.24.2-alpha"

    implementation "com.google.devtools.ksp:symbol-processing-api:1.7.10-1.0.6"

}
```

**Comment by linean** [comment]
I see you use incorrect `compose-destinations` version. It should match your Compose version. Checkout step 2 in the readme: https://github.com/raamcosta/compose-destinations#2-add-the-dependencies

<img width="380" alt="image" src="https://user-images.githubusercontent.com/17886739/182541030-33670e43-723c-4295-8092-1a2e160bb449.png">

**Comment by linean** [comment]
I've also noticed your Compose version doesn't match Kotlin version. Make sure to set it up correctly: https://developer.android.com/jetpack/androidx/releases/compose-kotlin

**Comment by hoomanhooshyar** [comment]
Thank you so much
everything works fine now :)

**Comment by raamcosta** [comment]
Thanks a lot for helping out @linean 🙇‍♂️

Glad this is working now, I’ll close this 🙂

**Comment by lisonge** [comment]
```kts
    applicationVariants.all {
        addJavaSourceFoldersToModel(
            File(buildDir, "generated/ksp/$name/kotlin")
        )
    }
```

not working for my android studio but `gradle build` is ok

```kts
    sourceSets.configureEach {
        kotlin.srcDir("$buildDir/generated/ksp/$name/kotlin/")
    }
```

is work for my android studio and `gradle build`
