### ISSUE TITLE
Calling multiple DestinationsNavHost

### ISSUE THREAD

**Issue by Jparrgam** [raamcosta/compose-destinations#201]
hello, I have this error I am using version 1.5.8-beta but I am only using the generated graph, any idea why this error?
``` java
Fatal Exception: java.lang.IllegalStateException: Calling multiple DestinationsNavHost with a navigation graph containing the same route ('root')
       at com.ramcosta.composedestinations.utils.NavGraphRegistry$UniqueRouteCheckRunnable.run(NavGraphSpecHolder.kt:68)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8051)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by raamcosta** [comment]
Update to the latest versions. There was an issue with that assertion some versions back 🙂

**Comment by Jparrgam** [comment]
> Update to the latest versions. There was an issue with that assertion some versions back 🙂

thanks @raamcosta
