### ISSUE TITLE
Getting IllegalStateException on trying to navigate after screen rotation.

### ISSUE THREAD

**Issue by bharath1997** [raamcosta/compose-destinations#227]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.something.test, PID: 13709
    java.lang.IllegalStateException: no event down from INITIALIZED
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:142)
        at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
        at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.kt:183)
        at androidx.navigation.NavBackStackEntry.setMaxLifecycle(NavBackStackEntry.kt:156)
        at androidx.navigation.NavController.updateBackStackLifecycle$navigation_runtime_release(NavController.kt:987)
        at androidx.navigation.NavController.dispatchOnDestinationChanged(NavController.kt:892)
        at androidx.navigation.NavController.navigate(NavController.kt:1730)
        at androidx.navigation.NavController.navigate(NavController.kt:1662)
        at androidx.navigation.NavController.navigate(NavController.kt:1984)
        at androidx.navigation.NavController.navigate$default(NavController.kt:1979)
        at androidx.navigation.NavController.navigate(NavController.kt:1965)
        at com.ramcosta.composedestinations.navigation.DestinationsNavController.navigate(DestinationsNavController.kt:27)
        at com.ramcosta.composedestinations.navigation.DestinationsNavigator$DefaultImpls.navigate(DestinationsNavigator.kt:40)
        at com.ramcosta.composedestinations.navigation.DestinationsNavController.navigate(DestinationsNavController.kt:13)
        at com.ramcosta.composedestinations.navigation.DestinationsNavigator$DefaultImpls.navigate$default(DestinationsNavigator.kt:35)
        at com.ob.main.MainViewModel.performNativeNavigation(MainViewModel.kt:470)
        at com.ob.main.MainActivityKt$handleNavigation$2.emit(MainActivity.kt:235)
        at com.ob.main.MainActivityKt$handleNavigation$2.emit(MainActivity.kt:227)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at kotlinx.coroutines.flow.SharedFlowImpl.tryEmit(SharedFlow.kt:400)
        at com.ob.main.presentation.login.TopAppBarKt$HomeAppBarContent$1$1.invoke(TopAppBar.kt:70)
        at com.ob.main.presentation.login.TopAppBarKt$HomeAppBarContent$1$1.invoke(TopAppBar.kt:67)
        at com.ob.main.ui.components.DynamicAppBarKt$DynamicAppBar$1$1$2.invoke(DynamicAppBar.kt:50)
        at com.ob.main.ui.components.DynamicAppBarKt$DynamicAppBar$1$1$2.invoke(DynamicAppBar.kt:43)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:153)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:142)
        at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:222)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
2022-08-23 18:02:30.413 13709-13709/com.sgd.nlo.dev E/AndroidRuntime:     at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:566)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:456)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:469)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:310)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:179)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:98)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:97)
        at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1321)
        at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1267)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1206)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4196)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
        at android.view.View.dispatchPointerEvent(View.java:14799)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6344)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6145)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5623)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5680)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5646)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5811)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5654)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5868)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5627)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5680)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5646)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5654)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5627)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8558)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8509)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8478)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8681)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
2022-08-23 18:02:30.413 13709-13709/com.sgd.nlo.dev E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c3c7911, Dispatchers.Main.immediate]
```

On adding on onlyIfResumed to true it doesn't crash but it doesn't navigate, but on removing it crashes with the above error.
here is the navigation part, There is a possibility even I could have missed something, but I suspect it is something related to lifecycle, but couldn't find actual cause for this
```kotlin
navigator.value?.navigate(
                            LoginScreenDestination
                        ) {
                            popUpTo(Screen.Home.route)
                        }
```

**Comment by raamcosta** [comment]
Hi!

This happens always if you navigate after rotating? Are you holding your NavController somewhere that outlives the activity, for example the ViewModel?

**Comment by raamcosta** [comment]
Closing this, as it is not directly related to compose destinations, but I’m glad to help you in the comments down below.

**Comment by bharath1997** [comment]
Hi @raamcosta, As you can see below I dont hold my navcontroller in viewmodel, i have it in my main composable which is called in on create
```kotlin
 override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        mainViewModel.clearCookies()
        lifecycleScope.launchWhenStarted {
            handleNavigation(
                mainViewModel = mainViewModel,
                limitsViewModel = limitsViewModel
            )
        }
        lifecycleScope.launchWhenStarted {
            repeatOnLifecycle(Lifecycle.State.STARTED) {
                setDeeplinkObserver(mainViewModel, applicationContext)
            }
        }
        //updateType = versionManager.isUpdateAvailable( BuildConfig.VERSION_NAME, onboardingViewModel.versionData.value?.latest_app_version)
        setContent {


            mainViewModel.managers.value =
                Managers(webManager, authManager, biometricManager, menuManager, versionManager)
            VersionUtils.baseVersionUrl = BuildConfig.VERSION_URL


            OpenBetAppTheme {

                MainApp(mainViewModel, limitsViewModel)
                
            }
        }
    }
``` 
There are some composable which share some viewmodels so had to pass it way down to app navigation where nav host and destination Nav host are written , Here is the main app
```kotlin
fun SportsApp(mainViewModel: MainViewModel, limitsViewModel: LimitsViewModel) {
    val context = LocalContext.current
    val activity = context.findActivity()
    val loginViewModel: LoginViewModel by viewModel()
    val onboardingViewModel: OnboardingViewModel by viewModel()
    val menuWebViewModel: MenuWebViewModel = androidx.lifecycle.viewmodel.compose.viewModel()
    Timber.d("SportsApp composing")
    mainViewModel.menuWebViewModel.value = menuWebViewModel
    LaunchedEffect(mainViewModel.sectionList) {
        activity?.let { setSectionListObserver(mainViewModel, loginViewModel.loginUiSection, it) }
    }

    LaunchedEffect(Unit) {
        mainViewModel.managers.value?.versionManager?.getVersion(
            onboardingViewModel.versionData,
            BuildConfig.VERSION_NAME,
            mainViewModel._showRecommVersionDialog,
            mainViewModel._showForceVersionDialog
        )
        mainViewModel.mainWebState.value =
            WebModel(
                url = mainViewModel.managers.value?.webManager?.buildMainPageUrl(
                    url = BuildConfig.MAIN_URL,
                    version = BuildConfig.VERSION_NAME,
                    pkgName = BuildConfig.APPLICATION_ID
                ),
                from = com.ob_core_framework.utils.Constants.WebModelConstants.FROM_SPORTS_BOOK
            )
        mainViewModel.currentWebModel.value = mainViewModel.mainWebState.value
    }

    val snackBarColor by remember { mainViewModel.snackBarColor }
    OpenBetAppTheme {
        val snackBarHostState = remember { SnackbarHostState() }
        val scaffoldState = rememberScaffoldState(snackbarHostState = snackBarHostState)
        val coroutineScope = rememberCoroutineScope()
        val navController = rememberAnimatedNavController()
        ObScaffold(
            snackBarColor,

            navController = navController,
            scaffoldState = scaffoldState,
            bottomBar = {
                //TODO use for future bottom navigation implementation
//                destination ->
//            BottomBar(
//                currentDestination = destination,
//                onBottomBarItemClick = {
//                    navController.navigate(it) {
//                        launchSingleTop = true
//                    }
//                }
//            )
            },
            drawerContent = { destination ->
                ObDrawer(
                    destination = destination,
                    navController = navController,
                    coroutineScope = coroutineScope,
                    scaffoldState = scaffoldState
                )
            }
        ) { paddingValues ->
            mainViewModel.uiErrorHandling(context)
            AppNavigation(
                modifier = Modifier.padding(paddingValues),
                drawerController = remember(scaffoldState) { DrawerControllerImpl(scaffoldState.drawerState) },
                navController = navController,
                scaffoldState = scaffoldState,
                coroutineScope = coroutineScope,
                mainViewModel,
                loginViewModel,
                onboardingViewModel,
                limitsViewModel
            )
            ConnectivityStatus(mainViewModel)
            SessionTimeoutAlert(mainViewModel, loginViewModel)
            ReceiveNotificationDialog(mainViewModel)
            RecommendedVersionAlert(
                mainViewModel = mainViewModel,
                onboardingViewModel = onboardingViewModel
            )
            ForceVersionAlert(
                mainViewModel = mainViewModel,
                onboardingViewModel = onboardingViewModel
            )
            ExternalLinkHandling(mainViewModel)
            LoginSettingsDialog(mainViewModel, loginViewModel)
            ConnectionComposable(mainViewModel, context)
        }
    }
}
```

However I have a navigator model a mutable shared flow being observed as sharedflow, my app is a multi module app, so don't want to pass nav controller way to down to modules so I am passing the navigator model to those then the module emits it with the respective value which is handled here. 

```kotlin
//Listening to navigation data change
suspend fun handleNavigation(
    mainViewModel: MainViewModel,
    limitsViewModel: LimitsViewModel
) {
    mainViewModel._navigatorModel.asSharedFlow().collect { navigatorModel ->
        mainViewModel.navigatorModel.value = navigatorModel
        Timber.e("inside handle navigation ${navigatorModel}")
        val navigationData = navigatorModel?.data
        if (navigationData != null) {
            when (navigationData.linkType) {
                com.ob_core_framework.utils.Constants.NATIVE -> {
                    mainViewModel.performNativeNavigation(
                        item = navigationData,
                        limitsViewModel = limitsViewModel
                    )
                }
                Constants.WEBLINK -> {
                    if (!navigationData.action.isNullOrEmpty()) {
                        when (navigationData.action) {
                            Constants.WebModelConstants.FROM_REGISTRATION -> {
                                mainViewModel.performWebNavigation(
                                    item = navigationData,
                                    BuildConfig.REG_SOURCE,
                                    extraDomain = navigatorModel.extraDomain
                                        ?: false
                                )
                            }
                            else -> {
                                mainViewModel.performWebNavigation(
                                    item = navigationData,
                                    extraDomain = navigatorModel.extraDomain
                                )
                            }
                        }
                    } else {
                        mainViewModel.performWebNavigation(
                            item = navigationData,
                            extraDomain = navigatorModel.extraDomain
                        )
                    }
                }
             
                else -> {
                    Timber.e("Unrecognized link type: ${navigationData.linkType}")
                }
            }
        }

        if (navigatorModel?.navigateBack == true) {
            mainViewModel.goHome()

        }
        if (navigatorModel != null || !navigatorModel?.uiActionFields?.successMessage.isNullOrEmpty() || !navigatorModel?.uiActionFields?.errorMessage.isNullOrEmpty()) {
            mainViewModel.handleNavigatorMessage(navigatorModel?.uiActionFields)
        }
    }


}
```

**Comment by bharath1997** [comment]
hey sorry for the trouble, found the issue, seems I am not setting the destination navigator value again after the rotation, moved it and works fine now thanks for the support

**Comment by raamcosta** [comment]
Nice!
