### ISSUE TITLE
@NavTypeSerializer is not visible when defined in another module

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#265]
I'm struggling with the architecture of passing an UUID as a destination parameter. 
I'm using an UUID as an argument, and the compiler wants to see a serializer for that type, but I've defined it in my common-navigation module which I include into my current module, and it still does not compile.
I'm now forced to copy and paste the serializer into each of these modules. The implementation of the serializer object simply delegates to an actual `UUIDSerializer`, which I obviously already have in my project, but it's defined in another module. 

Desired behavior:
I want to annotate a destination parameter with something like `@SerializeWith(UUIDSerializer::class)` just like it's done in the kotlinx.serialization library.

That would solve the visibility problem (which I assume you won't be able to fix), the duplication problem, architecture, and also allow for different serializers for each composable / parameter, unlike it's done now (what if I want to serialize something in different ways in 1 module?)

**Comment by Nek-12** [comment]
Okay, this is getting more complex by the minute...

UUID obviously implements java.io.Serializable. Documentation says custom serializers shouldn't be needed for these types, ok, but I get

```
[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Composable 'OngoingRitualScreen', arg name= 'ritualId': deep links cannot contain mandatory navigation types of custom type unless you definea custom serializer with @NavTypeSerializer. This lets you control how the custom type class is defined in the string route.
```

Defining a duplicate of the serializer as 
```
@NavTypeSerializer
object UUIDNavTypeSerializer : DestinationsNavTypeSerializer<Uuid> by UUIDNavTypeSerializer // from my nav module
```

now leads to the following:

```
[ksp] java.lang.ClassCastException: class com.google.devtools.ksp.symbol.impl.binary.KSTypeAliasDescriptorImpl cannot be cast to class com.google.devtools.ksp.symbol.KSClassDeclaration (com.google.devtools.ksp.symbol.impl.binary.KSTypeAliasDescriptorImpl and com.google.devtools.ksp.symbol.KSClassDeclaration are in unnamed module of loader java.net.URLClassLoader @449bf44b)
	at com.ramcosta.composedestinations.ksp.processors.Processor$getNavTypeSerializers$1.invoke(Processor.kt:85)
	at com.ramcosta.composedestinations.ksp.processors.Processor$getNavTypeSerializers$1.invoke(Processor.kt:65)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
	at com.ramcosta.composedestinations.ksp.processors.Processor.getNavTypeSerializers(Processor.kt:92)
	at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:30)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:287)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:285)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:390)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:285)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:124)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:100)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:265)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:158)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:99)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1645)
	at jdk.internal.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This is because I'm using a [multiplatform uuid](https://github.com/benasher44/uuid) where Uuid is defined as
```
public actual typealias Uuid = java.util.UUID
```
If I explicitly change the serializer to java.util.UUID it does not produce any error.

**Comment by raamcosta** [comment]
@Nek-12 the second error should be fixed with newest version of the library.

**Comment by Nek-12** [comment]
This also seems to be a duplicate of #173

**Comment by raamcosta** [comment]
Correct! Thanks @Nek-12 👍

closing this one
