### ISSUE TITLE
Function0 was requested, but it is not present

### ISSUE THREAD

**Issue by ForceGT** [raamcosta/compose-destinations#280]
**Context**

I was trying to integrate a bottom sheet with the destinations using animations core dependency and my root nav host is setup in this fashion

```
 val navController = rememberAnimatedNavController()
        val bottomSheetNavigator = rememberBottomSheetNavigator()
        navController.navigatorProvider += bottomSheetNavigator

        ModalBottomSheetLayout(
            bottomSheetNavigator = bottomSheetNavigator
        ) {
            DestinationsNavHost(
                navController = navController,
                navGraph = featureSplash.getCUJRootNavGraph(),
                engine = rememberAnimatedNavHostEngine(),
                dependenciesContainerBuilder = {
                    // The function returns SplashNavigator due to class visibility reasons.
                    // From the code perspective this is basically providing the `CriticalUserJourneyNavigator`.
                    // It can be resolved to all the interfaces that are implemented
                    // by the navigator while injecting in a screen.
                    dependency(featureSplash.getSplashNavigatorDependency(navController))
                },
            )
        }
```

**Entire log(if it gives more context)**:

```
2022-10-30 12:49:45.429 22708-22708/com.rapido.passenger.staging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rapido.passenger.staging, PID: 22708
    java.lang.RuntimeException: Function0 was requested, but it is not present
        at com.ramcosta.composedestinations.navigation.DestinationDependenciesContainer.require(DestinationDependenciesContainer.kt:98)
        at com.rapido.payment.presentation.ui.destinations.PaymentScreenDestination.Content(PaymentScreenDestination.kt:94)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.CallComposable(AnimatedNavHostEngine.kt:259)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.access$CallComposable(AnimatedNavHostEngine.kt:58)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addBottomSheetComposable$1.invoke(AnimatedNavHostEngine.kt:230)
        at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addBottomSheetComposable$1.invoke(AnimatedNavHostEngine.kt:229)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at com.google.accompanist.navigation.material.SheetContentHostKt$SheetContentHost$3.invoke(SheetContentHost.kt:150)
        at com.google.accompanist.navigation.material.SheetContentHostKt$SheetContentHost$3.invoke(SheetContentHost.kt:148)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:60)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
        at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
        at com.google.accompanist.navigation.material.SheetContentHostKt.SheetContentHost(SheetContentHost.kt:148)
        at com.google.accompanist.navigation.material.BottomSheetNavigator$sheetContent$1.invoke(BottomSheetNavigator.kt:199)
        at com.google.accompanist.navigation.material.BottomSheetNavigator$sheetContent$1.invoke(BottomSheetNavigator.kt:174)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1$5.invoke(ModalBottomSheet.kt:513)
        at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1$5.invoke(ModalBottomSheet.kt:388)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:134)
        at androidx.compose.material.SurfaceKt$Surface$1.invoke(Surface.kt:117)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
2022-10-30 12:49:45.435 22708-22708/com.rapido.passenger.staging E/AndroidRuntime:     at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:114)
        at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1.invoke(ModalBottomSheet.kt:341)
        at androidx.compose.material.ModalBottomSheetKt$ModalBottomSheetLayout$1.invoke(ModalBottomSheet.kt:326)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2375)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2643)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3260)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3238)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3238)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3203)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:771)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1031)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:125)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:534)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:503)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@3624989, androidx.compose.ui.platform.MotionDurationScaleImpl@c373d8e, StandaloneCoroutine{Cancelling}@21aa9af, AndroidUiDispatcher@167c1bc]
```

I actually intend to know what's wrong with what I did

**Comment by ForceGT** [comment]
https://www.youtube.com/watch?v=kiHNT15m4hw&ab_channel=AlexStyl

Followed this tutorial to setup bottom sheet with compose destinations

**Comment by raamcosta** [comment]
Hi @ForceGT !

Seems like your PaymentScreen needs a lambda to be passed in but you didn’t specify how to get it 🙂

Usually lambdas is something which you shouldn’t pass via dependency container though. So make sure you need it to be a lamda. If so, you can manually call the composable like this: 
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters/#manually-call-your-screen-composable

Let me know if this helps 🙂

**Comment by raamcosta** [comment]
Let me know if this helps you below! 🙂

**Comment by ForceGT** [comment]
Hey, thanks for the quick reply and you were right

**Comment by raamcosta** [comment]
Glad it helped you!
