### ISSUE TITLE
Support Array and ArrayList navigation arguments

### ISSUE THREAD

**Issue by knightsamir** [raamcosta/compose-destinations#29]
[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Composable 'AmountScreen': 'navArgsDelegate' cannot have arguments that are not navigation types.
	at com.ramcosta.composedestinations.codegen.commons.DestinationWithNavArgsMapper.getNavArgs(DestinationWithNavArgsMapper.kt:24)
	at com.ramcosta.composedestinations.codegen.commons.DestinationWithNavArgsMapper.map(DestinationWithNavArgsMapper.kt:12)
	at com.ramcosta.composedestinations.codegen.CodeGenerator.generate(CodeGenerator.kt:26)
	at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:44)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:186)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:184)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:278)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:184)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:86)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:252)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:243)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:243)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:90)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:56)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1574)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
@Parcelize
data class AmountScreenArgs(
    val sendingAmount: Float,
    val exchangeRate: Float,
    val purposeList: List<TransferPurpose>
):Parcelable


@Parcelize
data class TransferPurpose(
    val id: Int,
    val purpose: String,
    var is_selected:Boolean = false
): Parcelable


@ExperimentalMaterialApi
@ExperimentalCoilApi
@ExperimentalAnimationApi
@Composable
@Destination(navArgsDelegate = AmountScreenArgs::class)
fun AmountScreen(
    navigator: DestinationsNavigator,
    navController: NavController
) {
}
```

**Comment by raamcosta** [comment]
Hi @knightsamir ! Thanks for reporting :)

I see what the issue is: Lists are not Parcelable nor Serializable by nature. So technically they are not navigation argument types. If you define the arguments like this, it will fail at runtime because `List<TransferPurpose>` cannot be sent either as a nav argument.

Currently supported types as navigation arguments are:
- Enums
- Parcelable
- Serializable
- String, Int, Float, Long, Boolean

So basically Lists are not supported as navigation arguments because they themselves are not any of these types.
This is also the case with normal Compose Navigation, so at the moment it is expected.

That said, I did find an issue: if you declare it as `Array<TransferPurpose` it should work because `Array` is `Serializable` but it doesn't because so far I haven't needed to worry about generics and so the invoke method is not correctly generated.

> Btw `AmountScreenArgs` doesn't need to be Parcelable. All its constructor values need to be one of the above types, but the class is just wrapping the navigation arguments, we are not actually passing the class from one screen to the next :)

In conclusion, I do need to make changes. The minimum will be handling generics so that you can use Array and ArrayLists here (and any serializable generic class).

**Comment by knightsamir** [comment]
Ok thanks but just to confirm i am able to pass same list without using Destination(navArgs=...) by direclty passing it to composables parameter. I works that way so is this just limitation on this navArgs side?

**Comment by raamcosta** [comment]
No, you won't be able to do that either. The app will compile but it will crash when you navigate to that screen.
Unless you are manually calling the composable screen, but then this is not really a navigation argument.

Have you actually tested navigating to the screen?

**Comment by knightsamir** [comment]
Ok so i tested again to make sure and i am able to pass same list directly like below

```
navigator.navigate(AmountScreenDestination(amountScreenArgs))


@ExperimentalCoilApi
@ExperimentalAnimationApi
@Composable
@Destination
fun AmountScreen(
    navigator: DestinationsNavigator,
    navController: NavController,
    amountScreenArgs: AmountScreenArgs
) {
```

**Comment by raamcosta** [comment]
Ahhh now I get it! But this is not equivalent, this way you are only defining one navigation argument of type Parcelable.
Whereas before you were defining multiple navigation arguments:

```kotlin
    val sendingAmount: Float,
    val exchangeRate: Float,
    val purposeList: List<TransferPurpose>
```

☝️ these were your navigation arguments.

So the equivalent with navArgsDelegate would be:

```kotlin
data class AmountScreenNavArgs(
    val args: AmountScreenArgs
)
```

Hope this is clear now :) For a workaround until I support arrays and lists, if you need to use `navArgsDelegate`, then wrap the args in the a class and use that instead.

**Comment by raamcosta** [comment]
Basically, you need to understand, each argument of the Composable will be 1 navigation argument. Each constructor parameter of the "navArgsDelegate" class will also be 1 navigation argument.

**Comment by knightsamir** [comment]
OK so i tried your above tip and it works so to summarize

This works 


```
@Parcelize
data class TransferPurpose(
    val id: Int,
    val purpose: String,
    var is_selected:Boolean = false
): Parcelable

@Parcelize
data class AmountScreenArgs(
    val sendingAmount: Float,
    val exchangeRate: Float,
    val purposeList: List<TransferPurpose>
):Parcelable

data class AmountScreenNavArgs(
    val args: AmountScreenArgs)
)

@ExperimentalMaterialApi
@ExperimentalCoilApi
@ExperimentalAnimationApi
@Composable
@Destination(navArgsDelegate = AmountScreenNavArgs::class)
fun AmountScreen(
    navigator: DestinationsNavigator,
    navController: NavController
) {
}
```

But this doesn`t

```
@Parcelize
data class TransferPurpose(
    val id: Int,
    val purpose: String,
    var is_selected:Boolean = false
): Parcelable

@Parcelize
data class AmountScreenArgs(
    val sendingAmount: Float,
    val exchangeRate: Float,
    val purposeList: List<TransferPurpose>
):Parcelable


@ExperimentalMaterialApi
@ExperimentalCoilApi
@ExperimentalAnimationApi
@Composable
@Destination(navArgsDelegate = AmountScreenArgs::class)
fun AmountScreen(
    navigator: DestinationsNavigator,
    navController: NavController
) {
}
```

**Comment by miduch** [comment]
any update on this? thanks!

**Comment by raamcosta** [comment]
I’ve done some of the ground work but then some other things got prioritised and I haven’t had much time to work on new features.

Even so I expect to continue some time in near future 🙂
Do you have some reason for urgency? Notice there are workarounds like wrapping the list in a parcelable class

**Comment by miduch** [comment]
nope no urgency, but will need this feature soon-ish. hopefully official solution is available then :)

thanks!

**Comment by miduch** [comment]
@raamcosta any updates on this?

**Comment by raamcosta** [comment]
Not yet. Hopefully in the coming weeks 🙂

**Comment by miduch** [comment]
Ok thanks for quick reply. 

As temp workaround while waiting for official support, could DestinationsNavTypeSerializer be used for List ?

**Comment by raamcosta** [comment]
Don’t think so 🤔

You can create a Parcelable wrapper to the list and pass that. That would be my workaround.

**Comment by raamcosta** [comment]
Something like this:

```kotlin
@Parcelize
class ThingsList(
    val list: List<Things> 
) : Parcelable, List<Things> by list
```

**Comment by raamcosta** [comment]
It works, just tested it 🙂

**Comment by miduch** [comment]
can use this one for time being, looking forward to see solution which you mentioned is coming soon

**Comment by raamcosta** [comment]
@miduch and @knightsamir good news, next version will have this support 🎉 
I just finished pushing the changes to main branch :) 

It'll support:

Arrays and ArrayLists _(not Lists, just ArrayLists)_ of:
- Float (`FloatArray` ✅ , `Array<Float>` ❌)
- Int (`IntArray` ✅ , `Array<Int>` ❌)
- Boolean (`BooleanArray` ✅ , `Array<Boolean>` ❌)
- Long (`LongArray` ✅ , `Array<Long>` ❌)
- String
- Enums
- Parcelables
- Serializables
- Ktx Serializable (annotated with `@kotlinx.serialization.Serializable`)
- Custom nav arg types (types for which the user has defined a `@NavTypeSerializer`)

**Comment by raamcosta** [comment]
Done on 1.5.2-beta!

**Comment by renanboni** [comment]
hey @raamcosta I'm having a similar problem, I saw you pushed a new feature that would solve the OP question but in my case, I'm still struggling:

I have this class that I'll be passed as argument:

`data class WorkoutRoutineArgs(
    val isFromRegister: Boolean = false,
    val routine: List<WorkoutRoutine> = emptyList()
)`

where WorkoutRoutine is:

```
data class WorkoutRoutine(
    val type: TrainingType = TrainingType.NONE,
    val weekList: List<WeekHour> = emptyList(),
)
```
and WeekHour is:

```
data class WeekHour(
    val weekDay: WeekDay = WeekDay.UNKNOWN,
    val hour: String = ""
)
```

and I got this exception when building the app:

**_IllegalDestinationsSetup: Composable 'WorkoutRoutineScreen': 'navArgsDelegate' cannot have arguments that are not navigation types. (check argument 'routine')_**

I've tried to add **Serializable** (from java.io) annotation to the data classes but still, it didn't work. Any idea on this? Thanks again

**Comment by raamcosta** [comment]
https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments

Check here what types are considered nav arg types. Lists don’t work, but arrays of nav args types do.

**Comment by SammYWin** [comment]
Hello, Im still in the need of passing Lists as nav arg type. 
@raamcosta can you please kindly specify why is it a problem to implement just normal Lists? Cause usually people use Lists and not ArrayList etc

**Comment by raamcosta** [comment]
The nav args are put on a Bundle which only have APIs for storing ArrayList. If you check navigation for fragments you’ll see they have the same limitation.
What is the problem of using ArrayList though? ArrayList is still a List 🙂

**Comment by SammYWin** [comment]
Well, my whole project uses List and do you mean I should replace List to ArrayList in my every model in order to conveniently use nav args? Or do I just create a separate ...NavArg class and map List to ArrayList in there?

**Comment by raamcosta** [comment]
You should definitely have a dedicated class for NavArgs since they are meant only for navigation between two screens. Then when you call that Nav args class constructor you wrap your list in `ArrayList(yourlist)`.
