### ISSUE TITLE
Navigating outside of the nav graph and coming back breaks all but the root navController

### ISSUE THREAD

**Issue by SiavashB** [raamcosta/compose-destinations#306]
We are attempting to migrate our app one module at a time to Compose Navigation using your library.
We use a view model pattern and inject using Koin. 

sometimes one module needs to access a page in another module, like going from the messages page to a user profile. Now Imagine if the user profile page in this case has not been migrated to compose navigation yet, and thus we use our classic fragment based navigator to navigate to that fragment. 

If we perform this navigation, then come back, any subsequent navigations using navController/destinations (unless its done  at the root of nav graph*) Navigator crashes with the error

`java.lang.IllegalStateException: no event down from INITIALIZED
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:281)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.setCurrentState(LifecycleRegistry.java:121)
                                                                                                    	at androidx.navigation.NavBackStackEntry.updateState(NavBackStackEntry.kt:173)
                                                                                                    	at androidx.navigation.NavBackStackEntry.setMaxLifecycle(NavBackStackEntry.kt:150)
                                                                                                    	at androidx.navigation.NavController.updateBackStackLifecycle$navigation_runtime_release(NavController.kt:987)
                                                                                                    	at androidx.navigation.NavController.dispatchOnDestinationChanged(NavController.kt:892)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1726)`

`*` The weird thing is the navController at the root of the nav graph works fine, its only the navControllers that have been passed to the view models of the pages nested within the root that crash. 
Now keep in mind we pass the nav controllers to the view model via koin as such:

`getStateViewModel(parameters = { parametersOf(destinationsNavigator) })`

I dont know if it's koin that's fudging up the navController, or if it's something within your library that blows up when we navigate outside of the NavGraph.

I'm able to do a work around by creating a flows that send an event back to the root of the graph and do the navigation there, but its very boiler-platy, and it would really be nice if I could just pass the destinationsNavigator to my viewModels and have them navigate directly. Thanks in advance.

**Comment by raamcosta** [comment]
Hi @SiavashB !

I cannot deduce what exactly is going on, but I can tell you that you shouldn't be passing Navigators to ViewModel.
Either NavController or DestinationsNavigator (since it holds the NavController internally).

When activity gets recreated, a new NavController will be created and so using the old one will for sure lead to problems (as well as leaking the previous Activity I'm guessing).

Navigation shouldn't come from the ViewModel because only the UI knows about the UI. "Showing the next screen" can mean normal navigation or it can mean showing the detail part of a "two-pane" screen if the app is running on a tablet for example. This is valid for official compose navigation as well, there is nothing here particular to this library.

If you really must navigate from ViewModel, you need to come up with something like a global object with flow of navigation actions which then get consumed at the "NavHost call" level (as you said).

**Comment by raamcosta** [comment]
Let me know below if this was helpful! 🙂

**Comment by SiavashB** [comment]
Yes it was thank you. Yeah the problem was doing navigation from view model. The reason we needed to do this was because in some cases we needed to check certain conditions before navigation away from the page (like saving draft before leaving a page where user writes a message) and generally try to not have logic in our Ui files. 
But I created a SharedFlow to send navigation events back to the Ui. 
Thank you

**Comment by ymaniz09** [comment]
@raamcosta Do you believe it is possible to include in the doc that we shouldn't pass Navigators to ViewModel?

Our team had a discussion initially to avoid passing Navigators to ViewModels, but since we didn't find a strong argument to avoid it, we added it anyway.
Today, I headed this issue to solve some crashes 😄 
I believe if we have this in your doc, it will prevent other users from making the same mistake =]
