### ISSUE TITLE
Getting class cast exception randomly

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#361]
I am passing an array to a destination.
Array<T> where T is made Parcelize.
While passing, I convert the list to typedArray by using  someList.toTypedArray()

And the data class looks like this
@Parcelize
data class A(
    val Ab: String,
    var C: String?,
    val D: Int,
    val E: String?
) : Parcelable

It works normally, but randomly get the following error.

```
java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to xxx.YY[]
	at com.xxx.navtype.YYArrayNavType.get(YYArrayNavType.kt:29)
	at com.xxx.navtype.YYArrayNavType.get(YYArrayNavType.kt:18)
	at com.ramcosta.composedestinations.navargs.DestinationsNavType.safeGet(DestinationsNavType.kt:18)
	at com.xxx.destinations.AAADestination.argsFrom(AAADestination.kt:68)
	at com.xxx.destinations.AAADestination.argsFrom(AAADestination.kt:29)
	at com.ramcosta.composedestinations.scope.DestinationScopeImpl$navArgs$2.invoke(DestinationScopeInternals.kt:20)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at com.ramcosta.composedestinations.scope.DestinationScopeImpl.getNavArgs(DestinationScopeInternals.kt:19)
	at com.xxx.destinations.AAADestination.Content(AAADestination.kt:58)
	at com.ramcosta.composedestinations.DefaultNavHostEngine.CallComposable(DefaultNavHostEngine.kt:176)
	at com.ramcosta.composedestinations.DefaultNavHostEngine.access$CallComposable(DefaultNavHostEngine.kt:31)
	at com.ramcosta.composedestinations.DefaultNavHostEngine$addComposable$1.invoke(DefaultNavHostEngine.kt:121)
	at com.ramcosta.composedestinations.DefaultNavHostEngine$addComposable$1.invoke(DefaultNavHostEngine.kt:120)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.navigation.compose.NavHostKt$NavHost$4$2.invoke(NavHost.kt:163)
	at androidx.navigation.compose.NavHostKt$NavHost$4$2.invoke(NavHost.kt:162)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:162)
	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:141)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.animation.CrossfadeKt$Crossfade$4$1.invoke(Crossfade.kt:115)
	at androidx.compose.animation.CrossfadeKt$Crossfade$4$1.invoke(Crossfade.kt:110)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:124)
	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:55)
	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:141)
	at androidx.navigation.compose.NavHostKt$NavHost$5.invoke(Unknown Source:13)
	at androidx.navigation.compose.NavHostKt$NavHost$5.invoke(Unknown Source:10)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2351)
	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2641)
	at com.xxx.BBKt$NaviPayMainScreen$2.invoke(BB.kt:187)
	at com.xxx.BBinternal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:127)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2351)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2618)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3205)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3183)
	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3183)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3148)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:746)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1127)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:835)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1114)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8299)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@90bff33, androidx.compose.ui.platform.MotionDurationScaleImpl@64f62f0, StandaloneCoroutine{Cancelling}@5927069, AndroidUiDispatcher@7d00aee]
```

**Comment by raamcosta** [comment]
Hi @UKMIITB 

Can you give me a minimum sample that reproduces the issue? Thanks.

**Comment by raamcosta** [comment]
@UKMIITB can you help?

**Comment by UKMIITB** [comment]
@raamcosta 
Now I am not able to reproduce this. Have tried multiple ways but couldn't succeed.
Requesting you to mark this as closed for now. 
If in case I get some exact steps to be able to reproduce this, will re-open this issue with more info

**Comment by raamcosta** [comment]
Ok, let's do that thanks
