### ISSUE TITLE
[Crash] Race condition in appDestination() 

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#370]
The crash happened 2 times on a single device immediately on startup. This was not the first start.

Brand:realme
Model:RMX2040
Orientation: Portrait
RAM free: 1.3 GB
Version:Android 11
Orientation: Portrait
Rooted:No

Stacktrace:
```
Fatal Exception: java.lang.IllegalStateException: Cannot call NavBackStackEntry.destination() before DestinationsNavHost!
       at com.ramcosta.composedestinations.utils.SpecExtensionsKt.route(SpecExtensionsKt.java:48)
       at com.ramcosta.composedestinations.utils.SpecExtensionsKt.destination(SpecExtensionsKt.java:34)
       at com.nek12.respawn.common.navigation.SingleModuleExtensionsKt.appDestination(SingleModuleExtensionsKt.java:50)
       at com.nek12.respawn.common.navigation.SingleModuleExtensionsKt$special$$inlined$map$1$2.emit(SingleModuleExtensionsKt.java:224)
       at androidx.navigation.compose.NavHostKt$NavHost$lambda$4$$inlined$map$1$2.emit$bridge(Emitters.kt:856)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt)
       at kotlinx.coroutines.flow.ReadonlySharedFlow.collect(Share.kt:2)
       at com.nek12.respawn.common.navigation.SingleModuleExtensionsKt$special$$inlined$map$1.collect(SingleModuleExtensionsKt.java:113)
       at androidx.navigation.compose.NavHostKt$NavHost$lambda$4$$inlined$map$1.collect$bridge(SafeCollector.common.kt:135)
       at androidx.compose.runtime.SnapshotStateKt__SnapshotFlowKt$collectAsState$1.invokeSuspend(SnapshotFlow.kt:65)
       at androidx.compose.runtime.SnapshotStateKt__SnapshotFlowKt$collectAsState$1.invoke(SnapshotFlow.kt:12)
       at androidx.compose.runtime.SnapshotStateKt__ProduceStateKt$produceState$3.invokeSuspend(ProduceState.kt:151)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:255)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

It's very likely that the crash happened upon trying to initialize bottom bar navigation in the app. The bottom bar attempted to render itself before the navigation host was initialized fully(?). Inside itself, bottom bar wants to obtain current app destination to determine visibility and item selection state. Here's the code:

```
val navHostEngine = rememberAnimatedNavHostEngine(rootDefaultAnimations = DefaultNavAnimations())
val bottomSheetNavigator = rememberBottomSheetNavigator(skipHalfExpanded = true)
val navController = rememberAnimatedNavController().apply {
      navigatorProvider += bottomSheetNavigator
}
val currentDestination by navController.appCurrentDestinationAsState()
val showBottomBar = currentDestination in BottomBarDestinations
AppTheme(showBottomBar)
```
Anything I or maybe you can do to resolve this?

**Comment by Nek-12** [comment]
This issue is most likely related to an ANR another user recently experienced on startup:
```
at com.nek12.respawn.common.navigation.util.NavigationExtKt.getDestination(NavigationExt.kt:80)
       at com.nek12.respawn.common.navigation.util.NavigationExtKt.<clinit>(NavigationExt.kt:87)
       at com.nek12.respawn.common.navigation.RespawnNavigationKt.RespawnContent(RespawnNavigation.kt:73)
       at com.nek12.respawn.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:23)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
       at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:427)
       at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:226)
       at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:176)
       at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:226)
       at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:87)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:226)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
       at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm_jvmKt.java:78)
       at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(SnapshotStateKt__DerivedStateKt.java:334)
       at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3317)
       at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:584)
       at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:963)
       at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:517)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
       at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1070)
       at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
       at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:178)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:312)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:174)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
       at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1116)
       at android.view.View.dispatchAttachedToWindow(View.java:21976)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4293)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3474)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2924)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10513)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:797)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by raamcosta** [comment]
Hi @Nek-12 !

So sorry I missed this issue before..

```kotlin
val navHostEngine = rememberAnimatedNavHostEngine(rootDefaultAnimations = DefaultNavAnimations())
val bottomSheetNavigator = rememberBottomSheetNavigator(skipHalfExpanded = true)
val navController = rememberAnimatedNavController().apply {
      navigatorProvider += bottomSheetNavigator
}
val currentDestination by navController.appCurrentDestinationAsState()
val showBottomBar = currentDestination in BottomBarDestinations
AppTheme(showBottomBar)
```

I'm missing here the actual call to NavHost. Where does that happen?

**Comment by Nek-12** [comment]
Sorry, I tried to clean up the code, but made this more confusing

```
AppTheme(
        useDarkTheme = colorTheme.isDark ?: isSystemInDarkTheme(),
        useDynamicColors = dynamicColors,
    ) {
        ThemeSystemBars(
            darkMode = colorTheme.isDark ?: isSystemInDarkTheme(),
            enforceContrast = !showBottomBar
        )
        AppNavigation(
            navigator = bottomSheetNavigator,
            engine = navHostEngine,
            navController = navController,
            showNavBar = showBottomBar,
        )
    }
```

The actual code that comes in place of AppTheme() is above

AppNavigation looks like this:
```
@Composable
private fun AppNavigation(
    navigator: BottomSheetNavigator,
    engine: NavHostEngine,
    navController: NavHostController,
    showNavBar: Boolean,
) {
    val sheetElevation = Elevation.bottomSheet
    val bgColor = MaterialTheme.colorScheme.surfaceColorAtElevation(sheetElevation)

    // Wrap entire app in a bottom sheet in order to navigate to bottom sheets with destinations
    ModalBottomSheetLayout(
        bottomSheetNavigator = navigator,
        sheetElevation = sheetElevation,
        sheetBackgroundColor = bgColor,
        sheetContentColor = contentColorFor(bgColor).takeOrElse { MaterialTheme.colorScheme.onSurface },
        sheetShape = MaterialTheme.shapes.large.copy(bottomStart = CornerSize(0.dp), bottomEnd = CornerSize(0.dp)),
        scrimColor = MaterialTheme.colorScheme.scrim.copy(alpha = Opacity.scrim)
    ) {
        ResponsiveColumn(
            // avoid unthemed background
            modifier = Modifier
                .background(MaterialTheme.colorScheme.background)
                // try to avoid bottom sheet anchor bugs https://issuetracker.google.com/issues/178630869
                .sizeIn(minWidth = 1.dp, minHeight = 1.dp),
            columnArrangement = Arrangement.SpaceBetween,
            rowArrangment = Arrangement.SpaceBetween,
            columnAlignment = Alignment.Start,
            columnContent = {
                DestinationsNavHost(
                    // fill available space with destinations content
                    // make sure we have consumed our navbar insets since we're not using scaffold
                    modifier = Modifier.weight(1f),
                    navGraph = NavGraphs.root,
                    engine = engine,
                    navController = navController,
                    dependenciesContainerBuilder = {
                        dependency(currentNavigator)
                        dependency(rememberKoinInject<ScreenAnalytics>())
                    }
                )
                // animated bottom bar because it's hidden before the animation is finished
                AnimatedVisibility(showNavBar) {
                    AppNavigationBar(
                        onItemClick = navController.bottomBarHandler,
                        isSelected = navController.bottomBarSelectionHandler,
                    )
                }
            },
            rowContent = {
                // animated bottom bar because it's hidden before the animation is finished
                AnimatedVisibility(showNavBar) {
                    RNavigationBar(
                        onItemClick = navController.bottomBarHandler,
                        isSelected = navController.bottomBarSelectionHandler,
                    )
                }
                DestinationsNavHost(
                    // fill available space with destinations content
                    // make sure we have consumed our navbar insets since we're not using scaffold
                    modifier = Modifier
                        .weight(1f)
                        .fillMaxSize(),
                    navGraph = NavGraphs.root,
                    engine = engine,
                    navController = navController,
                    dependenciesContainerBuilder = {
                        dependency(currentNavigator)
                        dependency(rememberKoinInject<ScreenAnalytics>())
                    }
                )
            }
        )
    }
}
```

The helper functions look like this:

```
internal val NavController.bottomBarHandler
    get() = { it: NavigationBarItem ->
        if (it.destination != currentDestination) navigate(it.destination) {
            launchSingleTop = true
            restoreState = true
            popUpTo(NavGraphs.root) {
                inclusive = true
                saveState = true
            }
        }
    }

internal val NavController.bottomBarSelectionHandler: (NavigationBarItem) -> Boolean
    get() = { currentDestination?.route == it.destination.route }

internal val NavigationBarItem.destination: NavigationDirectionDestination
    get() = when (this) {
        Advice -> AdviceDestination
        Dashboard -> DashboardDestination
        Home -> HomeDestination
        Other -> SettingsDestination
    }

internal val BottomBarDestinations = NavigationBarItem.values().map { it.destination }.toSet()
```

P.S. To me this configuration looks like not-so-good code. Maybe you have some suggestions on how to make it better along the way.
P.P.S. You're putting the `help wanted` badge on issues, but I believe that badge means "I want someone to open a PR for this". The badge you're probably looking for is "Needs clarification" or similar

**Comment by raamcosta** [comment]
I think I understand what may be the cause. Thanks, I'll fix it for next release :) 

PS: No time to check it thoroughly

PSS: Description says "Extra attention needed" for so I think my usage is valid. Maybe for different repositories it will have a different meaning 😉

**Comment by Nek-12** [comment]
Thanks for such a quick fix!
