### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/animation/AnimatedContentScope;

### ISSUE THREAD

**Issue by miduch** [raamcosta/compose-destinations#402]
Following exception is thrown when trying to use compose-destinations 1.8.38-beta with 

accompanist  0.31.0-alpha
compose 1.5.0-alpha02

```
@Deprecated(
    "AnimatedContentScope has been renamed to AnimatedContentTransitionScope",
    replaceWith = ReplaceWith("AnimatedContentTransitionScope<S>")
)
 typealias AnimatedContentScope<S> = AnimatedContentTransitionScope<S>
```

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/animation/AnimatedContentScope;
     at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$toAccompanist$1.invoke(AnimatedNavHostEngine.kt:299)
     at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$finalEnter$1$1.invoke(AnimatedNavHost.kt:177)
     at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$finalEnter$1$1.invoke(AnimatedNavHost.kt:167)
     at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$7$1.invoke(AnimatedNavHost.kt:204)
     at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$7$1.invoke(AnimatedNavHost.kt:198)
     at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:759)
     at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:196)
     at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(Unknown Source:31)
     at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(Unknown Source:14)
     at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
     at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2467)
     at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2736)
     at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3352)
     at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3302)
     at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:776)
     at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1047)
     at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
     at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:541)
     at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
     at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
     at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
     at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
     at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
     at android.view.Choreographer.doCallbacks(Choreographer.java:899)
     at android.view.Choreographer.doFrame(Choreographer.java:827)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
     at android.os.Handler.handleCallback(Handler.java:942)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loopOnce(Looper.java:201)
     at android.os.Looper.loop(Looper.java:288)
     at android.app.ActivityThread.main(ActivityThread.java:7872)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by raamcosta** [comment]
There is no version for compose 1.5 yet. Stay tuned during next couple of days.

thanks for bringing this to my attention, last I checked there was no real 1.5 version yet.

**Comment by raamcosta** [comment]
1.9.39-beta cooking atm, should be in in next hour! Thanks again!

**Comment by Leeonardoo** [comment]
Just a heads-up, seems like it's still having issues with compose 1.5 even on 1.9.39-beta. I'm having this:

```
java.lang.NoSuchMethodError: No interface method enterTransition(Landroidx/compose/animation/AnimatedContentTransitionScope;)Landroidx/compose/animation/EnterTransition; in class
                 Lcom/ramcosta/composedestinations/spec/DestinationStyle$Animated; or its super classes (declaration of
                 'com.ramcosta.composedestinations.spec.DestinationStyle$Animated' appears in
                 /data/app/~~sBarv-M6xKajzPFE77YkPw==/br.com.myapp.debug-s-GovUEEYwOFAwg0J8tkRQ==/base.apk!classes22.dex)
                 	at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addAnimatedComposable$1$1.invoke(AnimatedNavHostEngine.kt:201)
                 	at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addAnimatedComposable$1$1.invoke(AnimatedNavHostEngine.kt:197)
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$finalEnter$1$1.invoke(AnimatedNavHost.kt:176)
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$finalEnter$1$1.invoke(AnimatedNavHost.kt:167)
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$7$1.invoke(AnimatedNavHost.kt:204)
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$7$1.invoke(AnimatedNavHost.kt:198)
                 	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:759)
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:196)
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(Unknown Source:27)
                 	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(Unknown Source:10)
...
```

I cloned the library, manually added the `androidx.compose.animation:animation:1.5.0-alpha02` dependency, replaced all `AnimatedContentScope` to `AnimatedContentTransitionScope` and it worked perfectly. So my guess it that somehow the library Is still trying to use an older version of the animation artifact even though it's using compose 1.5.0-alpha02 as without adding the dependency the `AnimatedContentTransitionScope` doesn't even exist

**Comment by rogerr99s** [comment]
Hello there, I'm in the same status...
Thank you in advance!

**Comment by raamcosta** [comment]
I’ll look into this probably tomorrow night. I accept PRs though 😅

**Comment by Leeonardoo** [comment]
I can a PR to this if you want @raamcosta . Is it fine if I include a direct dependency to the `animation` artifact? It seems like that's one of the issues

**Comment by raamcosta** [comment]
I’m hoping I can check this today. If not I’ll let you know 🙂

**Comment by raamcosta** [comment]
1.9.40-beta is cooking atm, should be up within the next 30min or so
