### ISSUE TITLE
Crash "java.lang.IllegalArgumentException: navigation destination ROUTE_NAME is not a direct child of this NavGraph" when I use accompanist 0.30.1

### ISSUE THREAD

**Issue by darkokoa** [raamcosta/compose-destinations#405]
This crash happened when my project accompanist was upgraded to 0.30.1.

Downgrade to 0.30.0 and everything works fine.

**Comment by raamcosta** [comment]
I don't fully understand the conditions. What accompanist dependency are you using?

**Comment by darkokoa** [comment]
Sorry, I forgot to mention this

I'm using

compose-destinations: 1.8.38-beta
kotlin: 1.8.10
compose-bom: 2023.03.00 (official compose-bom)

**Comment by raamcosta** [comment]
Ok and what are you using accompanist for?

**Comment by darkokoa** [comment]
For navigation animation

**Comment by darkokoa** [comment]
Just now, I upgraded accompanist to 0.30.1 in another project using vanilla navigation and it didn't get this crash

**Comment by raamcosta** [comment]
You don’t need to. This is a transitive dependency of compose destinations. Meaning if you also declare it as your own dependency, it will possibly bump the runtime dependency version and cause issues.

Simply remove accompanist and you should be fine 🙂

**Comment by raamcosta** [comment]
You will still have access to accompanist btw, just in case I wasn’t clear.
Let me know if that helps 🙂

**Comment by darkokoa** [comment]
I removed `accompanist-navigation-animation` and `accompanist-navigation-material` in my project, but the same crash still.

**Comment by raamcosta** [comment]
But if you use accompanist 0.30.0 it works? I don’t understand how that’s possible 😅

Try also bumping compose destinations version. There is a 1.8.39-beta since yesterday

**Comment by darkokoa** [comment]
Ok, I'll try it later

**Comment by raamcosta** [comment]
There is also a new bom version 2023.04.00

**Comment by Vlado24** [comment]
Hi @raamcosta thank you for this library, however I'm getting same error as @darkokoa - how did you solve it? 
Literally I was copy-pasting code from your https://github.com/raamcosta/tivi project - but I'm getting same error. (Try to update libs version in your project, but there was a plenty of work there (kotlin update and so on...)

I'm using this libraries and versions:
 ```
 kotlin("android").version("1.8.0").apply(false)
 id("com.google.devtools.ksp").version("1.8.0-1.0.9")
io.github.raamcosta.compose-destinations:animations-core:1.8.39-beta
io.github.raamcosta.compose-destinations:ksp:1.8.39-beta
```

Also I added this block of code into modules (multi-module project)
```
 ksp {
        arg("compose-destinations.moduleName", "home")
        arg("compose-destinations.mode", "destinations")
        arg("compose-destinations.generateNavGraphs", "false")
    }
```

Can you please investigate it more further?

Thanks,
Vlado

Full error:
```
FATAL EXCEPTION: main
                                                                                                    Process: com.project.vlado.android, PID: 27698
                                                                                                    java.lang.IllegalArgumentException: navigation destination test/test is not a direct child of this NavGraph
                                                                                                    	at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.kt:72)
                                                                                                    	at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.kt:49)
                                                                                                    	at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.kt:83)
                                                                                                    	at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.kt:49)
                                                                                                    	at androidx.navigation.NavController.navigateInternal(NavController.kt:260)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1719)
                                                                                                    	at androidx.navigation.NavController.onGraphCreated(NavController.kt:1161)
                                                                                                    	at androidx.navigation.NavController.setGraph(NavController.kt:1086)
                                                                                                    	at androidx.navigation.NavController.setGraph(NavController.kt:100)
                                                                                                    	at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:147)
                                                                                                    	at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:89)
                                                                                                    	at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.NavHost(AnimatedNavHostEngine.kt:84)
                                                                                                    	at com.ramcosta.composedestinations.DestinationsNavHostKt.DestinationsNavHost(DestinationsNavHost.kt:71)
                                                                                                    	at com.project.vlado.android.app.system.NavigationKt.AppNavigation(Navigation.kt:124)
                                                                                                    	at com.project.vlado.android.app.system.MainScreenKt$MainScreenContent$2$1$3.invoke(MainScreen.kt:174)
                                                                                                    	at com.project.vlado.android.app.system.MainScreenKt$MainScreenContent$2$1$3.invoke(MainScreen.kt:164)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
```

**Comment by raamcosta** [comment]
Hi @Vlado24 👋

There is not much for me to investigate. This error happens if your start destination is not a part of your NavGraph you pass in to DestinationsNavHost. In your case it seems to be test/test route.

If you want paste below some more code so I can try helping you further.

**Comment by Vlado24** [comment]
Thanks, here is my code:
This is Test destination in module named `test`. I have another module named `test1` where Test1 destination is.

```
@Destination
@Composable
fun Test(){
    Column(){
        Text("Test")
    }
}
```

```
@Destination
@Composable
fun Test1(){
    Column(){
        Text("Test 1")
    }
}
```

Then I've got `app` module where I connect it all together. This is `Navigation.kt` file:
```
object NavGraphs {

    val test = object : NavGraphSpec {
        override val destinationsByRoute = emptyMap<String, DestinationSpec<*>>()
        override val route = "test"
        override val startRoute = TestDestination routedIn this
    }

    val test1 = object : NavGraphSpec {
        override val destinationsByRoute = emptyMap<String, DestinationSpec<*>>()
        override val route = "test1"
        override val startRoute = Test1Destination routedIn this
    }

    val root = object : NavGraphSpec {
        override val route = "root"
        override val startRoute = test
        override val destinationsByRoute = emptyMap<String, DestinationSpec<*>>()
        override val nestedNavGraphs = listOf(
            test, test1
        )
    }
}

fun DependenciesContainerBuilder<*>.currentNavigator(): CommonNavGraphNavigator {
    return CommonNavGraphNavigator(
        navBackStackEntry.destination.navGraph(),
        navController
    )
}

@OptIn(ExperimentalMaterialNavigationApi::class)
@ExperimentalAnimationApi
@Composable
internal fun AppNavigation(
    navController: NavHostController,
    modifier: Modifier = Modifier,
) {
    DestinationsNavHost(
        engine = rememberAnimatedNavHostEngine(
            rootDefaultAnimations = RootNavGraphDefaultAnimations(
                enterTransition = { defaultEnterTransition(initialState, targetState) },
                exitTransition = { defaultExitTransition(initialState, targetState) },
                popEnterTransition = { defaultPopEnterTransition() },
                popExitTransition = { defaultPopExitTransition() },
            )
        ),
        navController = navController,
        navGraph = NavGraphs.root,
        modifier = modifier,
        dependenciesContainerBuilder = {
            dependency(currentNavigator())
        }
    )
}

@ExperimentalAnimationApi
private fun AnimatedContentScope<*>.defaultEnterTransition(
    initial: NavBackStackEntry,
    target: NavBackStackEntry,
): EnterTransition {
    val initialNavGraph = initial.destination.hostNavGraph
    val targetNavGraph = target.destination.hostNavGraph
    // If we're crossing nav graphs (bottom navigation graphs), we crossfade
    if (initialNavGraph.id != targetNavGraph.id) {
        return fadeIn()
    }
    // Otherwise we're in the same nav graph, we can imply a direction
    return fadeIn() + slideIntoContainer(AnimatedContentScope.SlideDirection.Start)
}

@ExperimentalAnimationApi
private fun AnimatedContentScope<*>.defaultExitTransition(
    initial: NavBackStackEntry,
    target: NavBackStackEntry,
): ExitTransition {
    val initialNavGraph = initial.destination.hostNavGraph
    val targetNavGraph = target.destination.hostNavGraph
    // If we're crossing nav graphs (bottom navigation graphs), we crossfade
    if (initialNavGraph.id != targetNavGraph.id) {
        return fadeOut()
    }
    // Otherwise we're in the same nav graph, we can imply a direction
    return fadeOut() + slideOutOfContainer(AnimatedContentScope.SlideDirection.Start)
}

private val NavDestination.hostNavGraph: NavGraph
    get() = hierarchy.first { it is NavGraph } as NavGraph

@ExperimentalAnimationApi
private fun AnimatedContentScope<*>.defaultPopEnterTransition(): EnterTransition {
    return fadeIn() + slideIntoContainer(AnimatedContentScope.SlideDirection.End)
}

@ExperimentalAnimationApi
private fun AnimatedContentScope<*>.defaultPopExitTransition(): ExitTransition {
    return fadeOut() + slideOutOfContainer(AnimatedContentScope.SlideDirection.End)
}

```

And in `MainScreen.kt` I have classic Scaffold with AppNavigation in row:
```
AppTheme {
    Background {
        val navController = rememberAnimatedNavController()
        val snackBarHostState: SnackbarHostState = remember { SnackbarHostState() }
        Scaffold(
            snackbarHost = { SnackbarHost(snackBarHostState) },
            containerColor = Color.Transparent,
            contentColor = MaterialTheme.colorScheme.onBackground,
            contentWindowInsets = WindowInsets(0, 0, 0, 0),
            bottomBar = {
                val currentSelectedItem by navController.currentScreenAsState()
                MainBottomNavigation(
                    selectedNavigation = currentSelectedItem,
                    onNavigationSelected = { selected ->
                        navController.navigateTo(selected) {
                            launchSingleTop = true
                            restoreState = true

                            popUpTo(navController.graph.findStartDestination().id) {
                                saveState = true
                            }
                        }
                    },
                    modifier = Modifier.fillMaxWidth()
                )
            },
        ) { padding ->
            Row(
                modifier = Modifier
                    .fillMaxSize()
                    .windowInsetsPadding(
                        WindowInsets.safeDrawing.only(
                            WindowInsetsSides.Horizontal
                        )
                    )
            ) {
                AppNavigation(
                    navController = navController,
                    modifier = Modifier
                        .weight(1f)
                        .fillMaxHeight()
                )
            }
        }
    }
}
```

Can you see any problems here please? Thanks ! 🙏
