### ISSUE TITLE
[ksp] NullPointerException | KspToCodeGenDestinationsMapper bottomSheetStyle

### ISSUE THREAD

**Issue by Hospes** [raamcosta/compose-destinations#415]
Hello Rafael,
First of all, I would like to thank you for this great library!!!

I have an issue with latest 2 versions: `1.9.40-beta` and `1.9.41-beta`
When I'm trying build the app I have this error stacktrace. With `1.9.39-beta` everything is going well.
I'm not using bottom sheets in the navigation anywhere in the app. There is only one bottom sheet used on the screen but not on the nav graph. So what could be wrong with it ?
```
> Task :app:kspQaDebugKotlin FAILED
e: [ksp] java.lang.NullPointerException
        at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper$bottomSheetStyle$2.invoke(KspToCodeGenDestinationsMapper.kt:438)
        at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper$bottomSheetStyle$2.invoke(KspToCodeGenDestinationsMapper.kt:437)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper.getBottomSheetStyle(KspToCodeGenDestinationsMapper.kt:437)
        at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper.getDestinationStyleType(KspToCodeGenDestinationsMapper.kt:274)
        at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper.toDestination(KspToCodeGenDestinationsMapper.kt:54)
        at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper.access$toDestination(KspToCodeGenDestinationsMapper.kt:13)
        at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper$map$1.invoke(KspToCodeGenDestinationsMapper.kt:24)
        at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper$map$1.invoke(KspToCodeGenDestinationsMapper.kt:24)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
        at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper.map(KspToCodeGenDestinationsMapper.kt:24)
        at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:43)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:291)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:289)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:394)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:289)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:257)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1486)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)

e: Error occurred in KSP, check log for detail
```

**Comment by raamcosta** [comment]
Are you using animations core or normal core dependency?

**Comment by Hospes** [comment]
I have there dependencies:
```
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }
```

**Comment by raamcosta** [comment]
Yap, 🐞  found 😋 

Thank you once again for reporting, I will make a new release with this fix right away.

**Comment by Nek-12** [comment]
Hey, I don't see 1.9.42 or 1.8.42 artifacts on Maven. Were they published?

**Comment by Nek-12** [comment]
Hey, I don't see 1.9.42 or 1.8.42 artifacts on Maven. Were they published?

**Comment by raamcosta** [comment]
There’s an issue with maven central. Should be fixed very soon. Release is only for 1.9 though as 1.8 didn’t have this issue

**Comment by raamcosta** [comment]
Yes, I was just now able to release it. Should be up within the next 30min or so.

**Comment by MaxMichel2** [comment]
Hello @raamcosta, I think this issue also applies to the Animated DestinationStyle in the 1.9.42 version (but works in 1.8.41)

**Comment by MaxMichel2** [comment]
> Hello @raamcosta, I think this issue also applies to the Animated DestinationStyle in the 1.9.42 version (but works in 1.8.41)

Sorry, my bad, I didn't notice the change in the naming, I thought this was still an extension!
