### ISSUE TITLE
[ksp] StackOverflowError | KspToCodeGenDestinationsMapper with AppCompat dependency

### ISSUE THREAD

**Issue by milkagaca** [raamcosta/compose-destinations#437]
Hello,

I have an issue with `1.8.41-beta` version. I recently needed to start using `AppCompatActivity` in project so I added dependency `androidx.appcompat:appcompat:1.6.1` and was using `1.7.34-beta` version of compose destinations. Soon after adding `AppCompat` I did an update to compose `1.4` along with bump for compose destinations to `1.8.41-beta` and I'm getting this error when building project:

```
e: java.lang.StackOverflowError
	at java.base/java.util.ArrayList.addAll(ArrayList.java:702)
	at kotlin.collections.CollectionsKt___CollectionsKt.plus(_Collections.kt:3227)
	at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper$getNavGraphInfo$relevantAnnotations$1.invoke(KspToCodeGenDestinationsMapper.kt:185)
	at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper$getNavGraphInfo$relevantAnnotations$1.invoke(KspToCodeGenDestinationsMapper.kt:183)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper.getNavGraphInfo(KspToCodeGenDestinationsMapper.kt:189)
	at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper.access$getNavGraphInfo(KspToCodeGenDestinationsMapper.kt:13)
	at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper$getNavGraphInfo$1.invoke(KspToCodeGenDestinationsMapper.kt:204)
	at com.ramcosta.composedestinations.ksp.processors.KspToCodeGenDestinationsMapper$getNavGraphInfo$1.invoke(KspToCodeGenDestinationsMapper.kt:203)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
        [...] (repeated several times)
```

I tried bumping `AppCompat` to `1.7.0-alpha1/alpha2` and it didn't help but downgrading compose navigation to previously used version (`1.7.34-beta`) solves the issue however I'll need to revert compose update with `1.3` as well which is not ideal.

I'm using:
`io.github.raamcosta.compose-destinations:core` and `io.github.raamcosta.compose-destinations:ksp`

Do you know what might be the issue here?

**Comment by raamcosta** [comment]
Hi @milkagaca 👋 

Yes, I think I know what the issue is. Since that version we're trying to check annotations recursively and it seems there is a loop with one of your annotations (line A -> annotated by B -> annotated by A or similar).

I need to find a definitive solution for this in the following days.

Thank you!

**Comment by milkagaca** [comment]
Great, thank you @raamcosta!

**Comment by raamcosta** [comment]
1.8.42-beta is cooking, please try it and let me know if it worked, I will be waiting to hear from you! 🙏

**Comment by milkagaca** [comment]
Just tested and it seems to be working, thank you so much @raamcosta for quick fix! 🎉

**Comment by raamcosta** [comment]
Great! Thanks for the feedback

**Comment by notdewie** [comment]
Version 1.8.42-beta no longer supports BottomSheet right @raamcosta ?

**Comment by raamcosta** [comment]
Yes it does. I’m guessing you are talking about the style that was moved because of changes in accompanist.
You can replace DestinationStyle.BottomSheet with DestinationStyleBottomSheet.

let me know if that fixes it for you.
