### ISSUE TITLE
How to navigate to a Destination from nested graphs

### ISSUE THREAD

**Issue by PrimozNChain** [raamcosta/compose-destinations#483]
I have 2 graphs. 1 root and 1 nested graph called settings graph. 
What I want to achieve is to open "Create PIN" Destination from root graph and from the settings graph. 

But I just get this error:
java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/create_pin_screen } cannot be found in the navigation graph NavGraph(0x98d0beb0) route=settings startDestination={Destination(0xd2a218db) route=settings_screen}

This is probably because it can belong to just 1 graph?

This is an example of Root:

```
@Destination
@Composable
fun MainScreen() {
val navController = rememberNavController()

    Scaffold {
        DestinationsNavHost(
            navGraph = NavGraphs.root,
            navController = navController,
        ) {
            composable(HomeScreenDestination) {
                HomeScreen(
                    onSettingsClick = {
                        navController.navigate(SettingsMainScreenDestination)
                    },
                )
            }
            composable(CreatePinScreenDestination) {
                CreatePinScreen(
                    onPinCreated = {
                        navController.navigateAndPopUpTo(HomeScreenDestination)
                    },
                )
            }
        }
    }
}
```

And this is example of Settings:
```
@Destination
@Composable
fun SettingsMainScreen() {
val navController = rememberNavController()

    Scaffold {
        DestinationsNavHost(
            navGraph = NavGraphs.settings,
            navController = navController,
        ) {
            composable(SettingsScreenDestination) {
                SettingsScreen(
                    onSetPinClick = {
                        navController.navigate(CreatePinScreenDestination)
                    },
                    onResetPinClick = { /*TODO*/ },
                    onBackClick = onBackClick,
                )
            }

            composable(CreatePinScreenDestination) {
                CreatePinScreen(
                    onPinCreated = {
                        navController.navigate(SettingsScreenDestination)
                    },
                )
            }
        }
    }
}
```

Create PIN and Settings is setup like:

```
@SettingsNavGraph(start = true)
@Destination
@Composable
fun SettingsScreen(
    onResetPinClick: () -> Unit,
    onDeleteClick: () -> Unit,
    onSignOut: () -> Unit,
    onBackClick: () -> Unit,
    viewModel: SettingsViewModel = hiltViewModel(),
) {
    val state by viewModel.uiState.collectAsState()
    SettingsScreenContent(
        state = state,
        onResetPinClick = onResetPinClick,
        onDeleteClick = onDeleteClick,
        onSignOut = onSignOut,
        onBackClick = onBackClick,
    )
}

@Destination
@Composable
fun CreatePinScreen(
    onPinCreated: () -> Unit,
    viewModel: CreatePinViewModel = hiltViewModel(),
) {
    val uiState by viewModel.uiState.collectAsState()
    CreatePinContent(
        state = uiState,
        onPinChange = viewModel::onNewPin,
        onPinRepeatChanged = viewModel::onRepeatPin,
        onPinCreated = onPinCreated,
    )
}
```

Oh and if you are wondering what is "navigateAndPopUpTo" it's just an extension (It makes it a bit more clean :)):

```
fun NavHostController.navigateAndPopUpTo(
    destination: DirectionDestination,
    @IdRes popUpToId: Int = graph.id,
) {
    navigate(destination.route) {
        popUpTo(popUpToId)
    }
}
fun NavHostController.navigateAndPopUpTo(
    destination: Direction,
    @IdRes popUpToId: Int = graph.id,
) {
    navigate(destination.route) {
        popUpTo(popUpToId)
    }
}
```

I had an idea to just have 2 Destinations for CreatePin, but with a slightly different name and with each their own annotation to which graph it belongs. But I don't want to do that, because then there will be a case where I need to use PIN to "verify" the screen on almost any screen and that just duplicates the code.

Another solution would be to have everything in RootGraph and that is that, but because there are a lot of screens that file can become very bloated and hard to read, that's why I wanted to seperate it into "flows" and each "flow" will have its own graph.

Thank you for the all the awesome work and help!

**Comment by raamcosta** [comment]
Hi @PrimozNChain 👋

I found this issue with the same question, let me know if my answer there helps!

https://github.com/raamcosta/compose-destinations/issues/310#issuecomment-1341762858

**Comment by raamcosta** [comment]
Another important answer in case you still want to have multiple nav hosts:

https://github.com/raamcosta/compose-destinations/issues/188#issuecomment-1193351202

**Comment by PrimozNChain** [comment]
Thanks for your quick response, I'll check it out!

**Comment by PrimozNChain** [comment]
I'm sorry to reopen this issue, but I couldn't find the "straightforward" answer in the documentation or in answers.
If I understand correctly, it is recommended to have just 1 `DestinationsNavHost`, where you have `navGraph = NavGraphs.root` and you have 1 navController.

I don't understand where do I put the second graph, if we don't have a another DesinationsNavHost? 
For example, in the "Official" navigation I think there is an option to define a "composable("some_destination")", and you can define other graphs with "navigation" like here: https://github.com/philipplackner/NestedNavigationGraphsGuide/blob/master/app/src/main/java/com/plcoding/nestednavigationgraphsguide/MainActivity.kt

but in this case I'm doing it wrong...

(this is wrong, but just an example):

```
fun NavGraphBuilder.settingsNavGraph(
    navController: NavHostController
) {
    navigation(
        route = NavGraphs.settings,
        startDestination = SettingsScreenDestination.route
    ){
            composable(SettingsScreenDestination) {
                SettingsScreen(
                    onSetPinClick = {
                        navController.navigate(CreatePinScreenDestination)
                    },
                    onDeleteClick = { /*TODO*/ },
                    onSignOut = { /*TODO*/ },
                    onBackClick = { /*TODO*/ },
                )
            }

            composable(CreatePinScreenDestination) {
                CreatePinScreen(
                    onPinCreated = {
                        navController.navigate(SettingsScreenDestination)
                    },
                )
            }
    }
}

```

To summarize of what I want to achieve:
- I want to have multiple graphs (for flows). 1 ROOT, others are nested.
- Access some Destinations from those nested graphs if necessary (authentication purposes) and then it should continue the flow (for this I created an extension function that gets backstack and gets from which one it was called from, then onSuccess it can continue, for example):
```
                LoginScreen(
                    onSignedIn = {
                        val route = navArgs.continueRouteWhenAuthenticated
                        if (route != null) {
                            navController.navigate(route)
                        } else {
                            navController.navigateAndPopUpTo(HomeScreenDestination)
                        }
                    },
```

I'm again sorry for not understanding your library correctly, because it really makes things a lot easier if it weren't for you. I just want to understand how to use it correctly and thank you for all the hard work!

**Comment by raamcosta** [comment]
Let me get back to you later, until then, this is how you can define nested graphs:

https://composedestinations.rafaelcosta.xyz/defining-navgraphs#generating-navigation-graphs

**Comment by raamcosta** [comment]
Hey @PrimozNChain !

Were you able to do what you wanted? I admit I maybe don't fully understand what exactly you want to accomplish, but nested graphs should be easy to accomplish after reading this link, I hope 😅

**Comment by PrimozNChain** [comment]
I didn't manage to solve it 😢.

I tried:

```
@Destination
@Composable
fun SettingsMainScreen() {
    val navController = rememberNavController()

    DestinationsNavHost(
        navGraph = NavGraphs.settings,
        navController = navController,
    ) {
        composable(SettingsScreenDestination) {
            SettingsScreen(
                onResetPinClick = {
                    navController.navigate(CreatePinScreenDestination)
                },
                onDeleteClick = { /*TODO*/ },
                onSignOut = { /*TODO*/ },
                onBackClick = {
                    navController.popBackStack()
                },
            )
        }
    }
}

```

This SettingsMainScreen should have another DestinationNavHost, but with the root NavGraphs.settings.

In the documentation it says:
"The most common use case, is to create nested navigation graphs inside root (like in the above SettingsNavGraph example) and pass NavGraphs.root to DestinationsNavHost".

But if I pass NavGraphs.root here, it just crashes with this stack:

 FATAL EXCEPTION: main
                                                                                                  
                                                                                                    java.lang.RuntimeException: Function0 was requested, but it is not present
                                                                                                    	at com.ramcosta.composedestinations.navigation.DestinationDependenciesContainerImpl.require(DestinationDependenciesContainer.kt:124)
                                                                                                    	at com.nchain.android.ui.destinations.SplashScreenDestination.Content(SplashScreenDestination.kt:47)
                                                                                                    	at com.ramcosta.composedestinations.DefaultNavHostEngine.CallComposable(DefaultNavHostEngine.kt:171)
                                                                                                    	at com.ramcosta.composedestinations.DefaultNavHostEngine.access$CallComposable(DefaultNavHostEngine.kt:31)
                                                                                                    	at com.ramcosta.composedestinations.DefaultNavHostEngine$addComposable$1.invoke(DefaultNavHostEngine.kt:116)
                                                                                                    	at com.ramcosta.composedestinations.DefaultNavHostEngine$addComposable$1.invoke(DefaultNavHostEngine.kt:115)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$4$2.invoke(NavHost.kt:173)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$4$2.invoke(NavHost.kt:172)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:172)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:146)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.CrossfadeKt$Crossfade$5$1.invoke(Crossfade.kt:133)
                                                                                                    	at androidx.compose.animation.CrossfadeKt$Crossfade$5$1.invoke(Crossfade.kt:128)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:142)
                                                                                                    	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:73)
                                                                                                    	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:146)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$5.invoke(Unknown Source:13)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$5.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2468)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2760)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:174)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$4.invoke(NavHost.kt:146)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
2023-08-06 17:58:06.274  7428-7428   	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.CrossfadeKt$Crossfade$5$1.invoke(Crossfade.kt:133)
                                                                                                    	at androidx.compose.animation.CrossfadeKt$Crossfade$5$1.invoke(Crossfade.kt:128)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.CrossfadeKt.Crossfade(Crossfade.kt:142)
                                                                                                    	at androidx.compose.animation.CrossfadeKt$Crossfade$7.invoke(Unknown Source:21)
                                                                                                    	at androidx.compose.animation.CrossfadeKt$Crossfade$7.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2468)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2737)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3352)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3303)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:827)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@3096a81, androidx.compose.ui.platform.MotionDurationScaleImpl@a3bd726, StandaloneCoroutine{Cancelling}@46c5f67, AndroidUiDispatcher@7e03114]

Here is an example of what I want to achieve (sorry for bad drawing).
![Untitled](https://github.com/raamcosta/compose-destinations/assets/124580486/89abe86b-d8c7-4054-b265-bf334a382a4d)


I guess I'm confused how to correctly use nested NavGraph with multiple DestinationsNavHost (for example here with Settings I'm not sure should the SettingsNavGraph have its own DestinationsNavHost, with NavGraphs.settings, or what is the correct usage). Oh maybe 1 more thing that can make things more clear, I edited the code in the original post.

Thank you for the help!

**Comment by raamcosta** [comment]
That crash seems to be because `SplashScreenDestination` takes a lambda as a parameter but you haven't specified how to get it.

Every parameter of Destination composables that is not a navigation argument, needs to be explicitly passed in from the NavHost level with these:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters (note how there is exception for common things like the NavController etc).

Assuming you are trying to have only one NavHost, and settings is nested inside root, then you absolutely need to be able to pass root to DestinationsNavHost. The graph passed in there needs to contain all destinations and nested graphs you want to include in that NavHost.

**Comment by PrimozNChain** [comment]
Hmm. I think I understand. 

That one crashes, because SplashScreen has a start=true and because i defined 2 DestinationsNavHost. Both have NavGraphs.root, but because it is expected to have a Lambda it crashes. If I want to fix it I need to define SplashScreen again, or remove its start = true?

I have a question about:
Better approach is to not send Lambdas, but to directly call another composable.

But with this approach, don't you lose the modularity of the screen, so it is completely independent? 
So far I only had root, and 1 DesinationsNavHost, where I could see all the navigation that is going to happen, which I liked. I'm afraid that if I move that navigation to inside the @Destination screen, then I lose that clarity. 
Do you maybe have any "Good practices" example or something like that :)?

**Comment by raamcosta** [comment]
> Better approach is to not send Lambdas, but to directly call another composable.

I said most common approach. Not necessarily the best. That would depend on your specific project.
If you want to have all navigation logic in one place, then you can still do that. But don’t forget to manually call all your screens that need some of these lambdas otherwise it will crash at runtime when navigating to that screen (or of course if it’s the start destination, as soon as you open the app).

> But with this approach, don't you lose the modularity of the screen, so it is completely independent?

I don’t think you loose anything, but I can see how in a small app having all navigation logic in one place might feel good. However the bigger the app the less convenient that will be (imagine having just dozens of screens there 😅), so splitting the nav logic at the screen or nav graph level will make more sense imo.

**Comment by PrimozNChain** [comment]
I understand :). So for small apps <10 screens this is a great approach, but for larger apps it is better to directly call the next screen from DestinationScreen.

What I still don't understand is DestinationsNavHost vs NavGraphs. For example in this case there there should be just 1 DestinationNavHost with NavGraphs.root set. But then it doesn't really matter that it is a nested graph for settings?

1. What is the use case for nested graphs, except for just popping the graph out from backstack when needed and how to use them correctly?
2. When should I use multiple DestinationNavHosts? (probably if the flows are completely separate and not needed to call on each other?)
3. Any examples with those usages? 

Thank you!

**Comment by raamcosta** [comment]
1. Yes and also to encapsulate unit of navigation. For example if one module is exposing just the nav graph instead of individual screens that are part of it.
2. Also if you really need to have a NavHost that has different UI boundaries. For example a set of screens that don't occupy the full screen and another which do.

You'll find examples using official compose navigation, and it should be fairly easy to adapt to this lib!

**Comment by PrimozNChain** [comment]
Ok thanks for the help!
