### ISSUE TITLE
Generated argsFrom() function can find only parameters that are of String type

### ISSUE THREAD

**Issue by Cuyer** [raamcosta/compose-destinations#506]
Hi,

I am trying to pass object from one screen to another, but only parameters of String type are being passed.

I have FeatureNavigator with navigateToScanningScreen() function as following:

```
  override fun navigateToScanningScreen() = navController.navigate(ScanningScreenDestination(User(
        name = "John",
        secondName = "Doe",
        age = 23
    )))
```

ScanningScreen is defined as following:

```
interface ScanningNavigator {

    fun navigateToCompletionScreen()

    fun navigateToExpeditionScreen()

    fun navigateToDashboardScreen()
}

data class User(
    val name: String,
    val secondName: String,
    val age: Int
)


@Destination(navArgsDelegate = User::class)
@Composable
fun ScanningScreen(
    navigator: ScanningNavigator,
) {
    ScanningDetails(viewModel = hiltViewModel())
}

@Composable
fun ScanningDetails(viewModel: ScanningViewModel) {

    Column(
        modifier = Modifier
            .fillMaxSize(),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text(text = "Scanning Screen ")
    }
}
```

And I am trying to retrieve this object in ViewModel as following:

```
@HiltViewModel
class ScanningViewModel @Inject constructor(
    val savedStateHandle: SavedStateHandle
) : ViewModel() {

    val args = ScanningScreenDestination.argsFrom(savedStateHandle)

    init {
        Log.d("User", "${args}")
    }
}
```

But only name and secondName parameters are present as these are Strings and age is of type Int.

ScanningScreenDestination generated class correctly assigns this object

```
    
	override val arguments: List<NamedNavArgument> get() = listOf(
		navArgument("name") {
			type = DestinationsStringNavType
		},
		navArgument("secondName") {
			type = DestinationsStringNavType
		},
		navArgument("age") {
			type = DestinationsIntNavType
		}
	)
```

But it throws exceptions anyway:

```
	override fun argsFrom(savedStateHandle: SavedStateHandle): User {
	    return User(
			name = DestinationsStringNavType.get(savedStateHandle, "name") ?: throw RuntimeException("'name' argument is mandatory, but was not present!"),
			secondName = DestinationsStringNavType.get(savedStateHandle, "secondName") ?: throw RuntimeException("'secondName' argument is mandatory, but was not present!"),
			age = DestinationsIntNavType.get(savedStateHandle, "age") ?: throw RuntimeException("'age' argument is mandatory, but was not present!"),
	    )
	}
```

**Comment by raamcosta** [comment]
Weird 🤔
What is the exception stacktrace?

**Comment by Cuyer** [comment]
```
FATAL EXCEPTION: main
                                                                                                    Process: com.example.demo, PID: 6877
                                                                                                    java.lang.RuntimeException: 'age' argument is mandatory, but was not present!
                                                                                                    	at com.example.demo.feature.scanning.presentation.destinations.ScanningScreenDestination.argsFrom(ScanningScreenDestination.kt:85)
                                                                                                    	at com.example.demo.feature.scanning.presentation.ScanningViewModel.<init>(ScanningViewModel.kt:15)
                                                                                                    	at
                                                                                                    com.example.demo.di.DaggerPelikanApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerPelikanApplication_HiltComponents_SingletonC.java:445)
                                                                                                    	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:102)
                                                                                                    	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.kt:90)
                                                                                                    	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:114)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                                                                                                    	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                                                                                                    	at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:215)
                                                                                                    	at androidx.lifecycle.viewmodel.compose.ViewModelKt.get$default(ViewModel.kt:195)
                                                                                                    	at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:120)
                                                                                                    	at com.example.demo.feature.scanning.presentation.ScanningScreenKt.ScanningScreen(ScanningScreen.kt:58)
                                                                                                    	at com.example.demo.feature.scanning.presentation.destinations.ScanningScreenDestination.Content(ScanningScreenDestination.kt:68)
                                                                                                    	at com.ramcosta.composedestinations.dynamic.DynamicDestinationSpecKt$routedIn$1.Content(Unknown Source:32)
                                                                                                    	at com.ramcosta.composedestinations.spec.DestinationStyleKt.CallComposable(DestinationStyle.kt:274)
                                                                                                    	at com.ramcosta.composedestinations.spec.DestinationStyleKt.access$CallComposable(DestinationStyle.kt:1)
                                                                                                    	at com.ramcosta.composedestinations.spec.DestinationStyleKt$addActivityDestination$1.invoke(DestinationStyle.kt:163)
                                                                                                    	at com.ramcosta.composedestinations.spec.DestinationStyleKt$addActivityDestination$1.invoke(DestinationStyle.kt:162)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:319)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:317)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:65)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:317)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14.invoke(NavHost.kt:301)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:138)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
2023-08-29 09:33:14.412  6877-6877  AndroidRuntime          com.example.demo                 E  	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$4.invoke(AnimatedContent.kt:780)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1$4.invoke(AnimatedContent.kt:769)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:941)
                                                                                                    	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:607)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:757)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6$1.invoke(AnimatedContent.kt:740)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:794)
                                                                                                    	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:279)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$18.invoke(Unknown Source:27)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$18.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2468)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2737)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3352)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3303)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:727)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by raamcosta** [comment]
Can you debug the navigate internal call and see how the route we pass to official lib looks like?

Can you try putting the arguments class in the screen composable and see if that has the same issue?

What version of the lib are you using?

(sorry for all the questions 😅)

**Comment by Cuyer** [comment]
1. I guess that the route should be :
```
override val route: String = "$baseRoute/{name}/{secondName}/{age}"
```
When I debug it, route of NavController has following value: 
```
scanning_screen/{name}/{secondName}/{age}/scanning_screen/{name}/{secondName}/{age}
```
_arguments of NavGraph are
```
name -> {NavArgument@20507} NavArgument Type: nav_type Nullable: false
secondName -> {NavArgument@20509} NavArgument Type: nav_type Nullable: false
age -> {NavArgument@20511} NavArgument Type: nav_type Nullable: false
```
2. I've tried passing User object, something similar to this:
```
@Composable
fun ScanningScreen(
    user: User,
    navigator: ScanningNavigator,
) {
    ScanningDetails(viewModel = hiltViewModel(), user)
}
```
But the issue still persisted. The error was something like the user is mandatory, but was not present
3. Version 1.9.52

**Comment by Cuyer** [comment]
Here is my NavGraphs object:

```
object NavGraphs {
    val dashboard = object : NavGraphSpec {
        override val destinationsByRoute: Map<String, DestinationSpec<*>>
            get() = listOf<DestinationSpec<*>>(
                DashboardScreenDestination,
                CompletionScreenDestination,
                ExpeditionScreenDestination,
                ScanningScreenDestination
            ).routedIn(this)
                .associateBy { it.route }
        override val route: String
            get() = DashboardScreenDestination.route
        override val startRoute: Route
            get() = DashboardScreenDestination routedIn this

    }

    val completion = object : NavGraphSpec {
        override val destinationsByRoute: Map<String, DestinationSpec<*>>
            get() = listOf<DestinationSpec<*>>(
                DashboardScreenDestination,
                CompletionScreenDestination,
                ExpeditionScreenDestination,
                ScanningScreenDestination
            ).routedIn(this)
                .associateBy { it.route }
        override val route: String
            get() = CompletionScreenDestination.route
        override val startRoute: Route
            get() = CompletionScreenDestination routedIn this

    }

    val expedition = object : NavGraphSpec {
        override val destinationsByRoute: Map<String, DestinationSpec<*>>
            get() = listOf<DestinationSpec<*>>(
                DashboardScreenDestination,
                CompletionScreenDestination,
                ExpeditionScreenDestination,
                ScanningScreenDestination
            ).routedIn(this)
                .associateBy { it.route }
        override val route: String
            get() = ExpeditionScreenDestination.route
        override val startRoute: Route
            get() = ExpeditionScreenDestination routedIn this

    }

    val scanning = object : NavGraphSpec {
        override val destinationsByRoute: Map<String, DestinationSpec<*>>
            get() = listOf<DestinationSpec<*>>(
                DashboardScreenDestination,
                CompletionScreenDestination,
                ExpeditionScreenDestination,
                ScanningScreenDestination
            ).routedIn(this)
                .associateBy { it.route }
        override val route: String
            get() = ScanningScreenDestination.route
        override val startRoute: Route
            get() = ScanningScreenDestination routedIn this

    }

    val root = object : NavGraphSpec {
        override val destinationsByRoute: Map<String, DestinationSpec<*>>
            get() = emptyMap<String, DestinationSpec<*>>()
        override val route: String
            get() = "root"
        override val startRoute: Route
            get() = dashboard

        override val nestedNavGraphs: List<NavGraphSpec>
            get() = listOf(
                dashboard,
                completion,
                expedition,
                scanning
            )
    }
}
```

**Comment by raamcosta** [comment]
Since each destination is registered in multiple nav graphs and you’re using routedIn, when you want to navigate, you need to specify which NavGraph you want to navigate to.

you can find an example in the routedIn functions kdocs but from the top of my head it’s something like `NavController.navigate(Destination(args) withIn NavGraph`

**Comment by raamcosta** [comment]
I’m surprised that that is the error you’re getting though 🤔
Let me know how it goes.

**Comment by Cuyer** [comment]
It works now. I really appreciate your help. I am really positively surprised how fast were your replies. Thank You.

One question though, I used Tivi as reference for navigation. I want to further use current implementation for bottom navigation bar. I suppose that declaring multiple nav graphs is necessary for it to work?

**Comment by raamcosta** [comment]
I was intrigued 😂

No, multiple NavGraphs is not necessary to have bottom bar navigation.
There is a section in the libs docs showing an example of bottom bar navigation.

https://composedestinations.rafaelcosta.xyz/common-use-cases/bottom-bar-navigation/

of course it may change a little bit if each option in the bottom bar is a NavGraph, also if using multi module app, etc.
