### ISSUE TITLE
Crash: Cannot call NavBackStackEntry.route() before DestinationsNavHost!

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#515]
<details>
 <summary>Stacktrace</summary>

```
Fatal Exception: java.lang.IllegalStateException:
       at com.ramcosta.composedestinations.utils.SpecExtensionsKt.route(SpecExtensions.kt:50)
       at com.ramcosta.composedestinations.utils.SpecExtensionsKt.destination(SpecExtensions.kt:36)
       at com.nek12.respawn.common.navigation.SingleModuleExtensionsKt.appDestination(SingleModuleExtensions.kt:51)
       at com.nek12.respawn.common.navigation.styles.BottomNavigationStyle.isCurrentToTheLeft(BottomNavigationStyle.kt:23)
       at com.nek12.respawn.common.navigation.styles.BottomNavigationStyle.getSlideDirection-kbud5bc(BottomNavigationStyle.kt:30)
       at com.nek12.respawn.common.navigation.styles.BottomNavigationStyle.getEnterTransition(BottomNavigationStyle.kt)
       at com.nek12.respawn.common.navigation.styles.BottomNavigationStyle.enterTransition(BottomNavigationStyle.kt)
       at com.ramcosta.composedestinations.spec.DestinationStyleKt$addActivityDestination$3.invoke(DestinationStyle.kt:197)
       at com.ramcosta.composedestinations.spec.DestinationStyleKt$addActivityDestination$3.invoke(DestinationStyle.kt:193)
       at androidx.navigation.compose.NavHostKt.createEnterTransition(NavHost.kt:346)
       at androidx.navigation.compose.NavHostKt.access$createEnterTransition(NavHost.kt:1)
       at androidx.navigation.compose.NavHostKt$NavHost$finalEnter$1$1.invoke(NavHost.kt:260)
       at androidx.navigation.compose.NavHostKt$NavHost$finalEnter$1$1.invoke(NavHost.kt:251)
       at androidx.navigation.compose.NavHostKt$NavHost$12.invoke(NavHost.kt:295)
       at androidx.navigation.compose.NavHostKt$NavHost$12.invoke(NavHost.kt:280)
       at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6.invoke(AnimatedContent.kt:823)
       at androidx.compose.animation.AnimatedContentKt$AnimatedContent$6.invoke(AnimatedContent.kt:775)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
       at androidx.compose.ui.layout.LookaheadScopeKt.LookaheadScope(LookaheadScope.kt:63)
       at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:775)
       at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:280)
       at androidx.navigation.compose.NavHostKt$NavHost$16.invoke(NavHost.kt:34)
       at androidx.navigation.compose.NavHostKt$NavHost$16.invoke(NavHost.kt:34)
       at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.java:192)
       at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2522)
       at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2814)
       at com.nek12.respawn.common.navigation.RespawnNavigationKt$RespawnNavigation$2$1.invoke(RespawnNavigation.kt:164)
       at com.nek12.respawn.common.navigation.RespawnNavigationKt$RespawnNavigation$2$1.invoke(RespawnNavigation.kt:143)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
       at com.nek12.respawn.common.ui.widgets.ResponsiveLayoutKt.ResponsiveLayout(ResponsiveLayout.kt:81)
       at com.nek12.respawn.common.ui.widgets.ResponsiveLayoutKt$ResponsiveLayout$1.invoke(ResponsiveLayout.kt:32)
       at com.nek12.respawn.common.ui.widgets.ResponsiveLayoutKt$ResponsiveLayout$1.invoke(ResponsiveLayout.kt:32)
       at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.java:192)
       at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2522)
       at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2791)
       at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3270)
       at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3221)
       at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:932)
       at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1143)
       at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:580)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:548)
       at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.java:109)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.java:41)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1410)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1420)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1047)
       at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:442)
       at android.view.Choreographer.doFrame(Choreographer.java:918)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1395)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8422)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

</details>

This affects roughly 1% of users.
This is not reproducible on Debug builds (or have not been able to reproduce due to small reproducibility rate)

Root composable code:

```
val navHostEngine = rememberAnimatedNavHostEngine(
        rootDefaultAnimations = DefaultNavAnimations(),
        navHostContentAlignment = Alignment.Center,
    )
    val bottomSheetNavigator = rememberBottomSheetNavigator(skipHalfExpanded = true)
    val navController = rememberNavController().apply {
        navigatorProvider += bottomSheetNavigator
    }
    val currentDestination = navController.appCurrentDestinationAsState()
    val showBottomBar by remember { derivedStateOf { currentDestination.value in BottomBarDestinations } }
    AppTheme {
        AppNavigation(
            currentDestination = currentDestination,
            navigator = bottomSheetNavigator,
            engine = navHostEngine,
            navController = navController,
            showNavBar = showBottomBar, // <- calls DestinationsNavHost and draws a bottom bar using an if() block
        )
    }
```

**Comment by raamcosta** [comment]
Hmm, what I think you can do here is to compare these via string routes instead of using appDestination, since it seems like it's possible that is called before NavHost. I cannot understand how that could be, but it seems like it's the case.

So, in `BottomNavigationStyle.isCurrentToTheLeft` instead of using `appDestination`, do `navBackStackEntry.destination.route` (all official APIs, not compose destinations) and compare the string routes with `MyDestination.route`.

Let me know if this helps :)

**Comment by Nek-12** [comment]
This app destination is troublesome in general. It also still causes a lot of ANRs and similar crashes #370

**Comment by raamcosta** [comment]
Closing this one @Nek-12 , let me know if you find it again after applying the suggestion!
