### ISSUE TITLE
[bug] wrong parsing of ResultRecipient when in two lines or typealiased

### ISSUE THREAD

**Issue by pawelsmagala** [raamcosta/compose-destinations#516]
when I have long type for ResultRecipient and autoformatter pushes it to next line, ksp failed.

Example:

```
@Destination()
@Composable
fun CreateScreen(
    processedCapturedMediaType:
    ResultRecipient<CaptureCameraScreenDestination, ProcessedMediaType?>,
) {
```

result in failure:
`[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Non existent Destination ('processedCapturedMediaType:') as the ResultRecipient's result origin!`

moving it back to one line fixes the issue:
```
@Destination()
@Composable
fun CreateScreen(
    processedCapturedMediaType:  ResultRecipient<CaptureCameraScreenDestination, ProcessedMediaType?>,
) {
```

Also using typealias to have shorter type definition fails:

```
typealias MediaRecipient =  ResultRecipient<CaptureCameraScreenDestination, ProcessedMediaType?>
@Destination()
@Composable
fun CreateScreen(
    processedCapturedMediaType: MediaRecipient,
) {
```
results in:

```

[ksp] java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
	at com.ramcosta.composedestinations.codegen.validators.InitialValidator.getFirstArgTypeSimpleName(InitialValidator.kt:234)
	at com.ramcosta.composedestinations.codegen.validators.InitialValidator.validateClosedResultRecipients(InitialValidator.kt:178)
	at com.ramcosta.composedestinations.codegen.validators.InitialValidator.validate(InitialValidator.kt:58)
	at com.ramcosta.composedestinations.codegen.CodeGenerator.generate(CodeGenerator.kt:34)
	at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:61)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:305)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:303)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:409)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:303)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1497)
```

**Comment by raamcosta** [comment]
1.9.54 is building which fixes this issue.

**Comment by hozrotbelal** [comment]
Make Result back feature work between different modules....Please write the code from different module such as: ScreenA,ScreenB and ScreenC. ScreenB and ScreenC is different Module. I want to result back ScreenA but how it will be solved it?
@destination()
https://github.com/composable
fun VendorProfileScreen(
navBackStackEntry: NavBackStackEntry,
resultRecipient: ResultRecipient<ScreenB, Boolean> // this line how to include ScreenC
)
This is the scenario. @raamcosta

**Comment by pawelsmagala** [comment]
> Make Result back feature work between different modules....Please write the code from different module such as: ScreenA,ScreenB and ScreenC. ScreenB and ScreenC is different Module. I want to result back ScreenA but how it will be solved it? @destination() https://github.com/composable fun ScreenA( navBackStackEntry: NavBackStackEntry, resultRecipient: ResultRecipient<ScreenB, Boolean> // this line how to include ScreenC ) This is the scenario. @raamcosta

you need to use OpenResultRecipient<Boolean> as described here https://composedestinations.rafaelcosta.xyz/navigation/backresult#multi-module-result-back-case
