### ISSUE TITLE
e: [ksp] java.lang.NullPointerException

### ISSUE THREAD

**Issue by knightsamir** [raamcosta/compose-destinations#52]
at com.ramcosta.composedestinations.codegen.writers.CustomNavTypesWriter.getNavTypeName(CustomNavTypesWriter.kt:192)
	at com.ramcosta.composedestinations.codegen.writers.CustomNavTypesWriter.generateCustomNavType(CustomNavTypesWriter.kt:50)
	at com.ramcosta.composedestinations.codegen.writers.CustomNavTypesWriter.write(CustomNavTypesWriter.kt:43)
	at com.ramcosta.composedestinations.codegen.CodeGenerator.generate(CodeGenerator.kt:28)
	at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:44)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:195)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:193)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:287)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:193)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
	at jdk.internal.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by knightsamir** [comment]
This occurs when i make Country as nullable like below 

```
@Composable
@Destination
fun CountryListScreen(
    navigator: DestinationsNavigator,
    resultNavigator: ResultBackNavigator<Country>,
    country: Country?
) {
```

Also i have other screens where i have nullable types like see below and it works fine there but somehow for above case it throws that error

```
@Composable
@Destination
fun AmountScreen(
    navigator: DestinationsNavigator,
    fraudWarningResultRecipient: ResultRecipient<FraudWarningScreenDestination, Boolean>,
    resultBackNavigator: ResultBackNavigator<AmountData>,
    amountData: AmountData?,
    country: Country
) {
```

In this above case it works without that error

**Comment by raamcosta** [comment]
Hi @knightsamir 

Thanks for reporting. I know where the problem is 🙂
I had already fixed this before on the branch where I'm working on arrays and list support but I honestly didn't remember to bring the fix to main branch.

I will fix it right now and make a new release with the fix.
Please retry it and let me know if it works 🙂

**Comment by raamcosta** [comment]
@knightsamir done.

Try version 1.2.2-beta and please confirm that it is working 🙂

**Comment by knightsamir** [comment]
Will try and report later
