### ISSUE TITLE
Multiple result recipients no longer supported in 1.9.57

### ISSUE THREAD

**Issue by harry248** [raamcosta/compose-destinations#558]
After updating to 1.9.57 we get the following compile time error:

`[ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Composable 'X' must receive a ResultBackNavigator of type 'String?' in order to be used as result originator for 'Y'`

The composable Y looks like this

```
@Composable
internal fun Y(
    resultRecipient1: ResultRecipient<Destination1, Boolean>,
    resultRecipient2: ResultRecipient<Destination2, String?>,
```

The composable X (Destination1) like this:

```
@Composable
fun X(
    resultBackNavigator: ResultBackNavigator<Boolean>,
```

Of course, there is another composable Z (Destination2) that has a `ResultBackNavigator<String?>`.

Was this change intended or is it a bug?

**Comment by raamcosta** [comment]
Hi @harry248 👋 

Thanks for reporting. It looks like a bug indeed. Let me check this today, I’ll release a fix for it.

**Comment by raamcosta** [comment]
Hey @harry248 I actually cannot reproduce this, can you paste here the exact code you're using? Maybe changing sensitive class names, but I need all the details including the formatting around the ResultRecipients, etc.

**Comment by raamcosta** [comment]
This is what I have added to test, but it works fine:

```kotlin
@Destination
@Composable
internal fun Y(
    resultRecipient1: ResultRecipient<XDestination, Boolean>,
    resultRecipient2: ResultRecipient<ZDestination, String?>,
) {

    resultRecipient1.onNavResult {
        println("$it")
    }

    resultRecipient2.onNavResult {
        println("$it")
    }
}

@Destination
@Composable
fun X(
    resultBackNavigator: ResultBackNavigator<Boolean>,
) {

    LaunchedEffect(Unit) {
        resultBackNavigator.navigateBack(result = true)
    }
}

@Destination
@Composable
fun Z(
    resultBackNavigator: ResultBackNavigator<String?>,
) {

    LaunchedEffect(Unit) {
        resultBackNavigator.navigateBack(result = null)
    }
}
```

**Comment by raamcosta** [comment]
@harry248 

So, I was able to reproduce it with something like this:

```kotlin
@Destination
@Composable
internal fun Y(
    resultRecipient1: ResultRecipient
    <XDestination, Boolean>,
    resultRecipient2: ResultRecipient<ZDestination, String?>,
) {

    resultRecipient1.onNavResult {
        println("$it")
    }

    resultRecipient2.onNavResult {
        println("$it")
    }
}
```

where "ResultRecipient" and "<" are not in the same line, can you confirm this is what you have? 

PS: I know formatting is a weird dependency to have on this logic, but this specific case requires me to actually parse these lines manually a little bit, so I missed this case the last time I touched in the logic 😬

**Comment by harry248** [comment]
The formatting looks like this, so the diamond brackets are in the same line.

```
@Composable
fun FirstScreen(
    resultBackNavigator: ResultBackNavigator<Boolean>,
    viewModel: SomeViewModel = hiltViewModel(),
) {
```

And

```
@Composable
internal fun SecondScreen(
    firstRecipient: ResultRecipient<FirstScreenDestination, Boolean>,
    secondRecipient: ResultRecipient<SecondScreenDestination, String?>,
    viewModel: SomeViewModel = hiltViewModel(),
) {
```

**Comment by raamcosta** [comment]
I still cannot reproduce it 🤔 

Is the only change you did between working version and non-working the version update?

In any case, since I found another way to reproduce it, maybe I will release a fix for that, and ask you to retry it. I'll also add some "info" level logs and ask you to run ksp task with --info and send me the logs, if you still facing this issue.

**Comment by raamcosta** [comment]
@harry248 can you please retest with 1.9.58 and if you still have the same issue, send me the output of running ksp task with --info (obviously replacing the sensitive names, but please keep them coherent, i.e all instances of a given name be replaced with the same thing)?
 
something like `./gradlew kspDebugKotlin --info` probably.. it depends on your variants, modules, etc

**Comment by harry248** [comment]
Unfortunately the error is still present. And yes, the change from 1.9.56 to 1.9.57/1.9.58 was the only one causing it. Here is the ksp part of the log (with --info):

```
i: [ksp] loaded provider(s): [dagger.hilt.processor.internal.uninstallmodules.KspUninstallModulesProcessor$Provider, dagger.hilt.processor.internal.earlyentrypoint.KspEarlyEntryPointProcessor$Provider, dagger.hilt.processor.internal.root.KspComponentTreeDepsProcessor$Provider, dagger.hilt.android.processor.internal.bindvalue.KspBindValueProcessor$Provider, dagger.hilt.processor.internal.generatesrootinput.KspGeneratesRootInputProcessor$Provider, dagger.hilt.processor.internal.aliasof.KspAliasOfProcessor$Provider, dagger.hilt.processor.internal.aggregateddeps.KspAggregatedDepsProcessor$Provider, dagger.hilt.processor.internal.root.KspRootProcessor$Provider, dagger.hilt.processor.internal.originatingelement.KspOriginatingElementProcessor$Provider, dagger.hilt.processor.internal.definecomponent.KspDefineComponentProcessor$Provider, dagger.hilt.android.processor.internal.viewmodel.KspViewModelProcessor$Provider, dagger.hilt.android.processor.internal.customtestapplication.KspCustomTestApplicationProcessor$Provider, dagger.hilt.android.processor.internal.androidentrypoint.KspAndroidEntryPointProcessor$Provider, com.ramcosta.composedestinations.ksp.ProcessorProvider, dagger.internal.codegen.KspComponentProcessor$Provider]
i: [ksp] validateClosedResultRecipients | checking param MapMainScreen resultRecipient
i: [ksp] getFirstArgTypeSimpleName | line error = "    resultRecipient: ResultRecipient<LocationPermissionDelegateScreenDestination, Boolean>,    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}"
i: [ksp] getFirstArgTypeSimpleName | result of removePrefix ResultRecipient = "<LocationPermissionDelegateScreenDestination, Boolean>,    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}"
i: [ksp] getFirstArgTypeSimpleName | result of removePrefix < = "LocationPermissionDelegateScreenDestination, Boolean>,    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}"
i: [ksp] getFirstArgTypeSimpleName | result of removeSuffix > = "LocationPermissionDelegateScreenDestination, Boolean"
i: [ksp] getFirstArgTypeSimpleName | result of split = "[LocationPermissionDelegateScreenDestination,  Boolean]"
i: [ksp] getFirstArgTypeSimpleName | Result of trim = "LocationPermissionDelegateScreenDestination"
i: [ksp] validateClosedResultRecipients | checking param MapMainScreen activateShoppingPassScreenResultRecipient
i: [ksp] getFirstArgTypeSimpleName | line error = "    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}@NavTypeSerializer"
i: [ksp] getFirstArgTypeSimpleName | result of removePrefix ResultRecipient = ": ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}@NavTypeSerializer"
i: [ksp] getFirstArgTypeSimpleName | result of removePrefix < = "ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}@NavTypeSerializer"
i: [ksp] getFirstArgTypeSimpleName | result of removeSuffix > = "ActivateShoppingPassScreenDestination, String?"
i: [ksp] getFirstArgTypeSimpleName | result of split = "[ActivateShoppingPassScreenDestination,  String?]"
i: [ksp] getFirstArgTypeSimpleName | Result of trim = "ActivateShoppingPassScreenDestination"
i: [ksp] validateClosedResultRecipients | checking param MapNestedScreen resultRecipient
i: [ksp] getFirstArgTypeSimpleName | line error = "internal fun MapNestedScreen(    resultRecipient: ResultRecipient<LocationPermissionDelegateScreenDestination, Boolean>,    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}"
i: [ksp] getFirstArgTypeSimpleName | result of removePrefix ResultRecipient = "<LocationPermissionDelegateScreenDestination, Boolean>,    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}"
i: [ksp] getFirstArgTypeSimpleName | result of removePrefix < = "LocationPermissionDelegateScreenDestination, Boolean>,    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}"
i: [ksp] getFirstArgTypeSimpleName | result of removeSuffix > = "LocationPermissionDelegateScreenDestination, Boolean"
i: [ksp] getFirstArgTypeSimpleName | result of split = "[LocationPermissionDelegateScreenDestination,  Boolean]"
i: [ksp] getFirstArgTypeSimpleName | Result of trim = "LocationPermissionDelegateScreenDestination"
i: [ksp] validateClosedResultRecipients | checking param MapNestedScreen activateShoppingPassScreenResultRecipient
i: [ksp] getFirstArgTypeSimpleName | line error = "internal fun MapNestedScreen(    resultRecipient: ResultRecipient<LocationPermissionDelegateScreenDestination, Boolean>,    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}"
i: [ksp] getFirstArgTypeSimpleName | result of removePrefix ResultRecipient = "<LocationPermissionDelegateScreenDestination, Boolean>,    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}"
i: [ksp] getFirstArgTypeSimpleName | result of removePrefix < = "LocationPermissionDelegateScreenDestination, Boolean>,    activateShoppingPassScreenResultRecipient: ResultRecipient<ActivateShoppingPassScreenDestination, String?>,    viewModel: MapScreenViewModel = hiltViewModel(),) {    MapScreen(        viewModel = viewModel,        resultRecipient = resultRecipient,        activateShoppingPassScreenResultRecipient = activateShoppingPassScreenResultRecipient,    )}"
i: [ksp] getFirstArgTypeSimpleName | result of removeSuffix > = "LocationPermissionDelegateScreenDestination, Boolean"
i: [ksp] getFirstArgTypeSimpleName | result of split = "[LocationPermissionDelegateScreenDestination,  Boolean]"
i: [ksp] getFirstArgTypeSimpleName | Result of trim = "LocationPermissionDelegateScreenDestination"
e: [ksp] com.ramcosta.composedestinations.codegen.commons.IllegalDestinationsSetup: Composable 'LocationPermissionDelegateScreen' must receive a ResultBackNavigator of type 'String?' in order to be used as result originator for 'MapNestedScreen'
        at com.ramcosta.composedestinations.codegen.validators.InitialValidator.validateClosedResultRecipients(InitialValidator.kt:198)
        at com.ramcosta.composedestinations.codegen.validators.InitialValidator.validate(InitialValidator.kt:58)
        at com.ramcosta.composedestinations.codegen.CodeGenerator.generate(CodeGenerator.kt:34)
        at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:61)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:306)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:304)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:410)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:304)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
        at jdk.internal.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
        at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
        at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

e: Error occurred in KSP, check log for detail
```

**Comment by raamcosta** [comment]
Is 

`resultRecipient` and `activateShoppingPassScreenResultRecipient` in the same line? 🤔 

Once again, thank you so much for helping, and sorry about this too 🙏

**Comment by raamcosta** [comment]
Can you tell me your kotlin and ksp versions?

**Comment by harry248** [comment]
No they aren't on the same line. Kotlin version is 1.9.21 and KSP is 1.9.21-1.0.16.
In any case, thanks for your effort!

**Comment by raamcosta** [comment]
Please test with 1.9.59, I will post here when it is available.

**Comment by harry248** [comment]
It works now! Thanks for the quick fix!
