### ISSUE TITLE
After updating some Gradle libraries including this one I get "BackendException: Backend Internal error: Exception during psi2ir" on a RootNavGraphDefaultAnimations implementation

### ISSUE THREAD

**Issue by alonsd** [raamcosta/compose-destinations#563]
I have the following Activity in my app - 

```
class ApplicationActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setAqvContent {
            val windowMetrics: WindowMetrics = WindowMetricsCalculator.getOrCreate().computeCurrentWindowMetrics(LocalContext.current as Activity)
            val screenWidth: Int = windowMetrics.bounds.width()
            DestinationsNavHost(
                navGraph = NavGraphs.root,
                engine = rememberAnimatedNavHostEngine(
                    navHostContentAlignment = Alignment.Center,
                    rootDefaultAnimations = rootNavGraphDefaultAnimations(screenWidth)
                )
            )
        }
    }
}
```

And the following RootNavGraphDefaultAnimations implementation - 

```
@OptIn(ExperimentalAnimationApi::class)
fun rootNavGraphDefaultAnimations(screenWidth: Int) = RootNavGraphDefaultAnimations(
    enterTransition = {
        slideInHorizontally(
            initialOffsetX = { screenWidth },
            animationSpec = tween(700)
        )
    },
    exitTransition = {
        slideOutHorizontally(
            targetOffsetX = { -screenWidth },
            animationSpec = tween(700)
        )
    },
    popEnterTransition = {
        slideInHorizontally(
            initialOffsetX = { -screenWidth },
            animationSpec = tween(700)
        )
    },
    popExitTransition = {
        slideOutHorizontally(
            targetOffsetX = { screenWidth },
            animationSpec = tween(700)
        )
    }
)
```

This implementation has worked fine for a project that has not been touched in around 8 months ±. Recently I started updating in all of that project's Gradle dependencies versions which include Kotlin version, KSP version and of course this library version. After doing so and syncing the same implementation that worked before the version updates stopped working with the following error - 

> org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during psi2ir
> File being compiled: (12,9) in /Users/...path/ScreenAnimations.kt
> The root cause org.jetbrains.kotlin.psi2ir.generators.ErrorExpressionException was thrown at: org.jetbrains.kotlin.psi2ir.generators.ErrorExpressionGenerator.generateErrorCall(ErrorExpressionGenerator.kt:100)
> null: KtCallExpression:
> slideInHorizontally(
>             initialOffsetX = { screenWidth },
>             animationSpec = tween(700)
>         )

Also, after each of the RootNavGraphDefaultAnimations named arguments (enterTransition, exitTransition, popEnterTransition, popExitTransition) I have an android studio compiler error saying:

>  this: [Error type: Inconsistent type AnimationContentScope<NavBackStackEntry> (parameters.size = 0, argument.size = 1)

![image](https://github.com/raamcosta/compose-destinations/assets/29747936/ad9ca3d2-c3f1-4647-a68b-b939e2702408)

This was not like that before the dependencies update. 

Did anything internal in the library source code change in the past less then a year regarding the implementation of RootNavGraphDefaultAnimations? those "backend error" and "ErrorExpressionException" are not your typical day-to-day Kotlin / Android errors and they seem more like some hard to diagnose reflection errors. 
Googling out this kind of error leads to a variety of problems which are not specifically related to this library but to many issues that some got it fixed by rebuilding the project or invalidating cache but not for me. 

Hopefully I missed some minor thing with the Gradle updates.

**Comment by raamcosta** [comment]
Hi @alonsd 

Can you please tell me versions of:

compose destinations 
Kotlin
Ksp
Compose 
Compose compiler

thanks!

**Comment by alonsd** [comment]
Thank you for your response :) 

animations-core (compose destinations) = "1.8.42-beta"
kotlinGradlePlugin = "1.9.22"
KSP version 1.9.22-1.0.16
activity-compose = "1.8.2"
kotlinCompilerExtensionVersion = "1.5.8"

**Comment by raamcosta** [comment]
With compose I meant compose Ui, not compose activity 🙂

**Comment by alonsd** [comment]
> With compose I meant compose Ui, not compose activity 🙂

Seems like I don't have `compose-ui` but only `compose.ui:ui-tooling` which is 1.5.4 and was 1.4.0-alpha05

**Comment by alonsd** [comment]
@raamcosta I tested the default implementation of RootNavGraphDeaultAnimations like the following - 

```
class ApplicationActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setAqvContent {
            val windowMetrics: WindowMetrics = WindowMetricsCalculator.getOrCreate().computeCurrentWindowMetrics(LocalContext.current as Activity)
            val screenWidth: Int = windowMetrics.bounds.width()
            DestinationsNavHost(
                navGraph = NavGraphs.root,
                engine = rememberAnimatedNavHostEngine(
                    navHostContentAlignment = Alignment.Center,
                    rootDefaultAnimations = RootNavGraphDefaultAnimations()
                )
            )
        }
    }
}
```

And it produced the following error - 


```
 java.lang.ClassCastException: androidx.compose.animation.AnimatedContentTransitionScopeImpl cannot be cast to androidx.compose.animation.AnimatedContentScope
                                                                                                    	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$7$1.invoke(AnimatedNavHost.kt:198)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:787)
                                                                                                    	at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:196)
                                                                                                    	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(Unknown Source:27)
                                                                                                    	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(Unknown Source:10)
                                                                                                    	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:169)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2468)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2737)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3352)
                                                                                                    	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3303)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:781)
                                                                                                    	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1097)
                                                                                                    	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:124)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:569)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:827)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@b72ea0c, androidx.compose.ui.platform.MotionDurationScaleImpl@4857f55, StandaloneCoroutine{Cancelling}@a614d6a, AndroidUiDispatcher@b00725b]
```


This is a different error then the one I initially reported in this thread with my own custom animations. My idea was to first check the the bare minimum default implementation like suggested in the documentation, and even there there is still a crash. This time the crash leads to some failed casting.

**Comment by raamcosta** [comment]
Hi @alonsd 

If you're using compose, there's definitely a compose ui dependency.
Assuming the compose tooling version is the same, then, looking at the readme of this library, you'll see that you should be using 1.9.x to match 1.5.x compose.

**Comment by alonsd** [comment]
Going by the official docs the compose ui and compose tooling are separate and independent of each other, and the only one I have in the same category is compose material3 which has a version of 1.1.2 which makes me confused because I used the 1.9.x version of this library since my compose tooling is 1.5.x and everything worked back again. I'll just leave it like that without further investigating atm. 

Seems like Gradle did not automatically suggest the latest 1.9.x version for this library, which made me use incompatible versions and caused this entire mess. If the version suggestions has anything to do with this library it could be a good idea to give it a check. Nonetheless, thanks a lot for your time and effort to help me solve this issue.

**Comment by raamcosta** [comment]
The confusing part is that you’re saying you don’t have compose ui dependency. That’s as far as I know the main dependency to be able to use compose. I’m guessing you’re using 1.5.x, maybe it’s a transitive dependency from another module?

anyway, glad the issue is solved!
