### ISSUE TITLE
Incompatible with androidx.navigation 2.8.0-alpha06 and newer

### ISSUE THREAD

**Issue by kodebach** [raamcosta/compose-destinations#619]
When used with `androidx.navigation` version `2.8.0-alpha06` or newer, trying to call `navController.navigate` with one of the generated `Destination` classes crashes at runtime:

```
kotlinx.serialization.SerializationException: Serializer for class '***Destination' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
                                                                                                    
at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:278)
at kotlinx.serialization.SerializersKt.serializer(Unknown Source:1)
at androidx.navigation.NavController.generateRouteFilled(NavController.kt:1681)
at androidx.navigation.NavController.generateRouteFilled$default(NavController.kt:1673)
at androidx.navigation.NavController.navigate(NavController.kt:2435)
at androidx.navigation.NavController.navigate$default(NavController.kt:2430)
[rest of call stack from where navigate(***Destination) is called]
```

The cause of this crash seems to be that `compose-destinations` adds an extension function

```kotlin
fun NavController.navigate(
    direction: Direction,
    navOptionsBuilder: NavOptionsBuilder.() -> Unit = {}
)
```

but  version `2.8.0-alpha06` of `androidx.navigation` adds a new overload

```kotlin
@MainThread
@JvmOverloads
@ExperimentalSafeArgsApi
public fun <T : Any> navigate(
    route: T,
    navOptions: NavOptions? = null,
    navigatorExtras: Navigator.Extras? = null
)
```

which hides the extension function.

**Comment by raamcosta** [comment]
When using Compose Destinations, you should not depend directly on Compose Navigation. Compode Destinations already transitively provides this dependency.

So this is not a problem with current versions.

> I did notice this though for newer Compose Destinations versions. It is very unfortunate and I'll have no choice but to introduce some breaking changes
