### ISSUE TITLE
upgraded from 2.0.0-beta02 to 2.0.0-beta09

### ISSUE THREAD

**Issue by sceneren** [raamcosta/compose-destinations#652]
When I upgraded from 2.0.0-beta02 to 2.0.0-beta09, the following error occurred. I don't know how to fix it.
<img width="824" alt="image" src="https://github.com/raamcosta/compose-destinations/assets/6612998/637b55bb-9bca-4b9c-a3ad-300ab45bf8b7">

```@NavGraph<MainGraph>
@NavHostGraph(route = "tab_route")
annotation class TabGraph {
    @ExternalDestination<VideoTabScreenDestination>(start = true)
    @ExternalDestination<SquareTabScreenDestination>
    @ExternalDestination<TaskTabScreenDestination>
    @ExternalDestination<MineTabScreenDestination>()
    companion object Includes
}

**Comment by raamcosta** [comment]
Hi 👋 

have you tried a gradle clean?

**Comment by sceneren** [comment]
I have tried it, but it still happens when I build.

**Comment by raamcosta** [comment]
Weird.. if you go back to beta02 it works again?

It does look like something related to caching issues 🤔

**Comment by sceneren** [comment]
Yes, when I rolled back to beta02 everything worked fine.

**Comment by raamcosta** [comment]
I'm really sorry that I didn't get back to you until now 🙏 

Do you still have this issue? I don't see any change between beta02 and beta09 that could cause this (I may be missing something though 🤔 )

Because of this issue, it made me go ahead and do something that I wanted to have for some time: a kind of debugMode which will output all information about your setup to a debug.txt file. Then you can share that file with me and I'll be able to help you better.

You just need to wait for my next release to be able to use this mode. I'll add how to in the release notes.

Thank you!

**Comment by sceneren** [comment]
Thanks for your help, I will test it when you release the next version

**Comment by sceneren** [comment]
[6030e5d1_d29d_4f95_a50a_0dac6f324ea4.txt](https://github.com/user-attachments/files/16329962/6030e5d1_d29d_4f95_a50a_0dac6f324ea4.txt)

`[ksp] kotlin.io.FileAlreadyExistsException: /Users/scene/Documents/android_workspace/ProjectName/app/build/generated/ksp/debug/kotlin/com/ramcosta/composedestinations/generated/navgraphs/TabNavGraph.kt
	at com.google.devtools.ksp.common.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:154)
	at com.google.devtools.ksp.common.impl.CodeGeneratorImpl.createNewFile(CodeGeneratorImpl.kt:69)
	at com.ramcosta.composedestinations.ksp.codegen.KspCodeOutputStreamMaker.makeFile(KspCodeOutputStreamMaker.kt:35)
	at com.ramcosta.composedestinations.codegen.facades.CodeOutputStreamMaker$DefaultImpls.makeFile$default(CodeOutputStreamMaker.kt:7)
	at com.ramcosta.composedestinations.codegen.writers.sub.SingleNavGraphWriter.write(SingleNavGraphWriter.kt:161)
	at com.ramcosta.composedestinations.codegen.writers.sub.NavGraphsSingleObjectWriter.writeNavGraphTreeRecursively(NavGraphsSingleObjectWriter.kt:61)
	at com.ramcosta.composedestinations.codegen.writers.sub.NavGraphsSingleObjectWriter.write(NavGraphsSingleObjectWriter.kt:50)
	at com.ramcosta.composedestinations.codegen.writers.ModuleOutputWriter.write(ModuleOutputWriter.kt:27)
	at com.ramcosta.composedestinations.codegen.CodeGenerator.postValidateGenerate(CodeGenerator.kt:90)
	at com.ramcosta.composedestinations.codegen.CodeGenerator.generate(CodeGenerator.kt:73)
	at com.ramcosta.composedestinations.ksp.processors.Processor.process(Processor.kt:82)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:310)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:308)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:308)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:77)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

I changed the project name and package name in the log file

**Comment by raamcosta** [comment]
Is this the only file that gets generated? 🤔

**Comment by raamcosta** [comment]
Thank you 🙏

I will check this later today!

**Comment by raamcosta** [comment]
Btw I didn’t include this in release notes, but you have to do a clean build to make sure nothing is already generated before you run the app / build the project. And then the debug data will be complete.

Was this after a clean build?

(sorry 🙏)

**Comment by sceneren** [comment]
Of course, I have deleted all the files generated before the build

**Comment by raamcosta** [comment]
Great! I’ve also added this instructions to release notes now 👍

**Comment by raamcosta** [comment]
@sceneren is your `TabGraph` annotated with both `NavHostGraph` and `NavGraph<MainGraph>` ? 🤔 

I can see two inputs to my ksp task with the same path `package.name.router.graph.TabGraph` and they are literally exactly the same, except one is a NavHost and the other isn't, and the one who isn't is a nested graph in `MainGraph`.

Can you see anything on your side that would justify this?

**Comment by sceneren** [comment]
```@NavGraph<MainGraph>
@NavHostGraph(route = "tab_route")
annotation class TabGraph {
    @ExternalDestination<VideoTabScreenDestination>(start = true)
    @ExternalDestination<SquareTabScreenDestination>
    @ExternalDestination<TaskTabScreenDestination>
    @ExternalDestination<MineTabScreenDestination>()
    companion object Includes
}

I'm sorry, I added @NavGraph<MainGraph> and @NavHostGraph(route = "tab_route") to TabGraph, when I removed @NavGraph<MainGraph> it worked fine.

**Comment by raamcosta** [comment]
That explains it. Closing this then!

Btw, `NavHostGraph` is meant to generate graphs that should be passed in to a `DestinationsNavHost`!

So I assume you have two calls in differnt places to `DestinationsNavHost`, one you're passing `MainNavGraph` and the other you're passing `TabNavGraph`.
