### ISSUE TITLE
Could not find Navigator with name "BottomSheetNavigator". You must call NavController.addNavigator() for each navigation type

### ISSUE THREAD

**Issue by yoobi** [raamcosta/compose-destinations#657]
Hello,

This is to re-open the #532. I have the same issue I'm using 
```
// compose
def compose_version = "1.6.7"
implementation "androidx.compose.ui:ui:$compose_version"
implementation "androidx.compose.material:material:$compose_version"
implementation "androidx.compose.foundation:foundation:$compose_version"
implementation "androidx.compose.material:material-navigation:1.7.0-beta01"

def compose_destinations_version = "1.10.2"
implementation "io.github.raamcosta.compose-destinations:animations-core:$compose_destinations_version"
ksp "io.github.raamcosta.compose-destinations:ksp:$compose_destinations_version"
```

I wanted to use `androidx.compose.material.navigation.ModalBottomSheetLayout()` because `com.google.accompanist.navigation.material.ModalBottomSheetLayout` is [deprecated](https://google.github.io/accompanist/navigation-material/) but it seems that the version 1.10.2 is still using `com.google.accompanist.navigation` in internal

```
java.lang.IllegalStateException: Could not find Navigator with name "BottomSheetNavigator". You must call NavController.addNavigator() for each navigation type.
	at androidx.navigation.NavigatorProvider.getNavigator(NavigatorProvider.kt:67)
	at androidx.navigation.NavigatorProvider.getNavigator(NavigatorProvider.kt:49)
	at com.google.accompanist.navigation.material.NavGraphBuilderKt.bottomSheet(NavGraphBuilder.kt:60)
	at com.ramcosta.composedestinations.spec.DestinationStyleBottomSheetKt.addComposable(DestinationStyleBottomSheet.kt:52)
	at com.ramcosta.composedestinations.animations.AnimatedNavHostEngineKt$lambda$1.invoke(AnimatedNavHostEngine.kt:58)
	at com.ramcosta.composedestinations.animations.AnimatedNavHostEngineKt$lambda$1.invoke(AnimatedNavHostEngine.kt:57)
	at com.ramcosta.composedestinations.spec.DestinationStyleKt.addActivityDestination(DestinationStyle.kt:220)
	at com.ramcosta.composedestinations.DefaultNavHostEngine.composable(DefaultNavHostEngine.kt:123)
	at com.ramcosta.composedestinations.DestinationsNavHostKt.addNavGraphDestinations(DestinationsNavHost.kt:115)
	at com.ramcosta.composedestinations.DestinationsNavHostKt.access$addNavGraphDestinations(DestinationsNavHost.kt:1)
	at com.ramcosta.composedestinations.DestinationsNavHostKt$DestinationsNavHost$2.invoke(DestinationsNavHost.kt:77)
	at com.ramcosta.composedestinations.DestinationsNavHostKt$DestinationsNavHost$2.invoke(DestinationsNavHost.kt:71)
	at androidx.navigation.compose.NavHostKt.NavHost(NavHost.kt:390)
	at com.ramcosta.composedestinations.DefaultNavHostEngine.NavHost(DefaultNavHostEngine.kt:79)
	at com.ramcosta.composedestinations.DestinationsNavHostKt.DestinationsNavHost(DestinationsNavHost.kt:71)
```

Is it possible to use `androidx.compose.material.navigation` instead ?

**Comment by raamcosta** [comment]
You need to update to compose 1.7 to be able to use navigation material.

Actually you should not depend on navigation material directly. It is a transitive dependency of compose destinations.

For compose 1.6 related versions, it still uses accompanist and that won’t change. But it should not be a concern of yours. Just use this library and you get the functionality you want without caring where it comes from 🙂

closing this! Let me know if there’s any additional question 👍

**Comment by yoobi** [comment]
Hello, I've updated my compose to 1.7-beta06. I have removed all dependencies to navigation material, I'm using the transitive dependency of compose as you suggested.

I'm having issue migrating to material because `androidx.compose.material.ModalBottomSheetLayout` doesn't have a `bottomSheetNavigator`
```
fun androidx.compose.material.ModalBottomSheetLayout(
    sheetContent: @Composable ColumnScope.() -> Unit,
    modifier: Modifier = Modifier,
    sheetState: ModalBottomSheetState =
        rememberModalBottomSheetState(Hidden),
    sheetGesturesEnabled: Boolean = true,
    sheetShape: Shape = MaterialTheme.shapes.large,
    sheetElevation: Dp = ModalBottomSheetDefaults.Elevation,
    sheetBackgroundColor: Color = MaterialTheme.colors.surface,
    sheetContentColor: Color = contentColorFor(sheetBackgroundColor),
    scrimColor: Color = ModalBottomSheetDefaults.scrimColor,
    content: @Composable () -> Unit
)
```

Could you details how the migration should be done ?

**Comment by raamcosta** [comment]
So I assume all works now?

**Comment by yoobi** [comment]
Yes it does work now after fixing some breaking change

**Comment by raamcosta** [comment]
Ok thank you 🙏
