### ISSUE TITLE
Zero argument constructor is required for viewModel()

### ISSUE THREAD

**Issue by margarita-v** [raamcosta/compose-destinations#72]
For example:
```
@Destination
@Composable
fun ProfileScreen(viewModel: ProfileViewModel = androidx.lifecycle.viewmodel.compose.viewModel()) {
// ...
}

@HiltViewModel
class ProfileViewModel @Inject constructor(
    override val reducer: ProfileReducer,
    override val middleware: ProfileMiddleware
) : CustomViewModel() {
// ...
}

object NavGraphs {
    val profile = object : NavGraphSpec {
        override val route: String = "profile"
        override val startRoute: Route = ProfileScreenDestination routedIn this
        override val destinationsByRoute: Map<String, DestinationSpec<*>> =
            listOf(
                ProfileScreenDestination
            )
                .routedIn(this)
                .associateBy { it.route }
    }
}
```

If I call `ProfileScreen()` from other composable, it works just fine. But for navigation using `ProfileScreenDestination` I'm getting the error 
```
java.lang.RuntimeException: Cannot create an instance of class com.example.demo.profile.ProfileViewModel
at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
at androidx.lifecycle.viewmodel.compose.ViewModelKt.get(ViewModel.kt:87)
at androidx.lifecycle.viewmodel.compose.ViewModelKt.viewModel(ViewModel.kt:72)
at com.example.demo.profile.ProfileScreenKt.ProfileScreen(ProfileScreen.kt:46)
at com.example.demo.profile.destinations.ProfileScreenDestination.Content(ProfileScreenDestination.kt:27)

at com.ramcosta.composedestinations.dynamic.DynamicDestinationSpecKt$routedIn$1.Content(Unknown Source:28)
at com.ramcosta.composedestinations.DefaultNavHostEngine.CallComposable(DefaultNavHostEngine.kt:161)
at com.ramcosta.composedestinations.DefaultNavHostEngine.access$CallComposable(DefaultNavHostEngine.kt:28)
at com.ramcosta.composedestinations.DefaultNavHostEngine$addComposable$1.invoke(DefaultNavHostEngine.kt:108)
at com.ramcosta.composedestinations.DefaultNavHostEngine$addComposable$1.invoke(DefaultNavHostEngine.kt:107)
...
Caused by: java.lang.InstantiationException: java.lang.Class<com.example.demo.profile.ProfileViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
```

I can fix it and provide zero argument constructor for `ProfileViewModel`, but in my point of view it should work because `viewModel()` should be called by default. Am I doing something wrong?

UPD For some cases it's more convenient to inject params as constructor parametrs, so there is a big limitation here if error is present

**Comment by raamcosta** [comment]
This is not related to compose destinations, this would happen with normal navigation as well.

You need to use hiltViewModel() instead of viewModel(), as seen here for example:
https://stackoverflow.com/questions/65810194/cannot-create-an-instance-of-viewmodel-while-using-jetpack-compose-navigation

I’m closing this but please let me know if this solves your issue, so I can be sure.

**Comment by margarita-v** [comment]
Thank you, that's right 👍
