### ISSUE TITLE
Problem with koin Annotations

### ISSUE THREAD

**Issue by amirzeinaly** [raamcosta/compose-destinations#89]
Hi
I use koin Annotations for di
I use this sample to describe problem 
I use @KoinViewModel for define ViewModel in my app
Code working fine but when I remove comment this couse koin to remove TestScreenViewModel defination in my module
```
@KoinViewModel
class TestScreenViewModel(
    savedStateHandle: SavedStateHandle
) : ViewModel() {

//    private val args = TestScreenDestination.argsFrom(savedStateHandle)

    init {

    }
}
```

Stacktrace log :

```
org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'com.xxxx.ui.screen.test.TestScreenViewModel'. Check your definitions!
                            	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:304)
                            	at org.koin.core.scope.Scope.resolveValue(Scope.kt:274)
                            	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
                            	at org.koin.core.scope.Scope.get(Scope.kt:204)
                            	at androidx.lifecycle.StateViewModelFactory.create(StateViewModelFactory.kt:17)
                            	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
                            	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:169)
                            	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
                            	at org.koin.androidx.viewmodel.ViewModelResolverKt.resolveInstance(ViewModelResolver.kt:15)
                            	at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:67)
                            	at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel(ScopeExt.kt:53)
                            	at org.koin.androidx.viewmodel.scope.ScopeExtKt.getViewModel$default(ScopeExt.kt:45)
                            	at com.setaksoft.visiono.vendor.ui.screen.test.TestScreenKt.TestScreen(TestScreen.kt:41)
                            	at com.setaksoft.visiono.vendor.ui.screen.destinations.TestScreenDestination.Content(TestScreenDestination.kt:47)
                            	at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.CallComposable(AnimatedNavHostEngine.kt:281)
                            	at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine.access$CallComposable(AnimatedNavHostEngine.kt:57)
                            	at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addComposable$1.invoke(AnimatedNavHostEngine.kt:174)
                            	at com.ramcosta.composedestinations.animations.AnimatedNavHostEngine$addComposable$1.invoke(AnimatedNavHostEngine.kt:173)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9$1.invoke(AnimatedNavHost.kt:212)
                            	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9$1.invoke(AnimatedNavHost.kt:210)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                            	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
                            	at androidx.navigation.compose.NavBackStackEntryProviderKt.SaveableStateProvider(NavBackStackEntryProvider.kt:60)
                            	at androidx.navigation.compose.NavBackStackEntryProviderKt.access$SaveableStateProvider(NavBackStackEntryProvider.kt:1)
                            	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:52)
                            	at androidx.navigation.compose.NavBackStackEntryProviderKt$LocalOwnersProvider$1.invoke(NavBackStackEntryProvider.kt:51)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                            	at androidx.navigation.compose.NavBackStackEntryProviderKt.LocalOwnersProvider(NavBackStackEntryProvider.kt:47)
                            	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9.invoke(AnimatedNavHost.kt:210)
                            	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$9.invoke(AnimatedNavHost.kt:202)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
2022-04-06 13:44:45.899  E  	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:658)
                            	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:648)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:116)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:935)
                            	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedVisibility(AnimatedVisibility.kt:606)
                            	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:638)
                            	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1.invoke(AnimatedContent.kt:625)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                            	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:671)
                            	at com.google.accompanist.navigation.animation.AnimatedNavHostKt.AnimatedNavHost(AnimatedNavHost.kt:197)
                            	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(AnimatedNavHost.kt)
                            	at com.google.accompanist.navigation.animation.AnimatedNavHostKt$AnimatedNavHost$11.invoke(AnimatedNavHost.kt)
                            	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:140)
                            	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2158)
                            	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2404)
                            	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2585)
                            	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:2571)
                            	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:247)
                            	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source)
                            	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:2571)
                            	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2547)
                            	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:620)
                            	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:786)
                            	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:105)
                            	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:456)
                            	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:425)
                            	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
                            	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                            	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                            	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                            	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
                            	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                            	at android.view.Choreographer.doFrame(Choreographer.java:618)
                            	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                            	at android.os.Handler.handleCallback(Handler.java:751)
                            	at android.os.Handler.dispatchMessage(Handler.java:95)
                            	at android.os.Looper.loop(Looper.java:154)
                            	at android.app.ActivityThread.main(ActivityThread.java:6119)
                            	at java.lang.reflect.Method.invoke(Native Method)
                            	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Thank you for guiding me to solve this problem

**Comment by raamcosta** [comment]
Hey @amirzeinaly !

I really have no idea what could be happening, except for a wild guess that maybe their KSP generator runs before Compose Destinations' one, so at the time they are trying to generate their stuff, `TestScreenDestination` doesn't yet exist.
I think you need to contact them to see if they can help you any further than this.

I'll close this since this is not an issue with Compose Destinations. But let us discuss further in the comments below.

**Comment by raamcosta** [comment]
I have started a thread on koin channel over on Kotlin slack:
https://kotlinlang.slack.com/archives/C67HDJZ2N/p1649244683083109

Hopefully we will hear from them 🤞

**Comment by raamcosta** [comment]
Hi again @amirzeinaly!

So this seems to be working on my end. I created a "koin-annotations-test" branch if you want to checkout and try.
The real problem I'm having now is that Koin doesn't seem to have a way to pass the navigation arguments bundle to the ViewModel so that they're used in `SavedStateHandle`. This is super common so pretty sure this will come eventually (unless it already exists and I just can't find it).

So your commented line would not work regardless.
The workaround is to pass the navigation arguments from the @Composable screen.

**Comment by amirzeinaly** [comment]
I think the problem is in koin 1 line viewModel getter

I post all my code here

```
import androidx.compose.runtime.Composable
import org.koin.androidx.compose.getViewModel

@Composable
fun TestScreen(
    age : Int,
    vm : TestScreenViewModel = getViewModel()
) {
//    val vm by viewModel<TestScreenViewModel>()
}
```

```
import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import com.ramcosta.samples.destinationstodosample.ui.screens.destinations.TestScreenDestination
import org.koin.android.annotation.KoinViewModel

@KoinViewModel
class TestScreenViewModel(savedStateHandle: SavedStateHandle) : ViewModel() {

//    val args = TestScreenDestination.argsFrom(savedStateHandle)

}
```

**Comment by raamcosta** [comment]
Yes this code builds on my end just fine. It just crashes on runtime because Koin is not populating the saved state handle. They have a PR to fix this though
