### ISSUE TITLE
How to make a NavGraphSpec from two modules?

### ISSUE THREAD

**Issue by S-H-Y-A** [raamcosta/compose-destinations#90]
Before discussing the question, I want to thank you for making compose-destinations. It makes my project better.
I made two module and make @Destination(graph = "download") Composable function.
```

Download Module
	├CheckUpdateScreen.kt
	│	└@Destination(graph = "download", style = DialogStyle::class)
	│		 fun CheckUpdateDialog()
	│
	├ApkDownloadScreen.kt
	│	└@Destination(graph = "download")
	│		 fun DownloadScreen()
	│
	└build.gradle.kts
		ksp {
  			arg("compose-destinations.mode", "destinations")
			arg("compose-destinations.moduleName", "download")
		}

Core Module
	├ErrorDialogScreen.kt
	│	└@Destination(graph = "download", style = DialogStyle::class)
	│		 fun ErrorDialog()
	│
	└build.gradle.kts
		ksp {
  			arg("compose-destinations.mode", "destinations")
			arg("compose-destinations.moduleName", "download")
		}

App Module
	├MainActivity.kt
	│	└DestinationsNavHost(NavGraph.root) <- error
	│
	└build.gradle.kts
		ksp {
  			arg("compose-destinations.mode", "navGraphs")
			arg("compose-destinations.moduleName", "app")
		}

```
But, NavGraph was not generated.
If anyone has an idea, could you tell me what I should do?

**Comment by raamcosta** [comment]
Hi @S-H-Y-A !

So you have to understand that KSP doesn't know KSP generated files from other modules. So in your app module if you don't generate any `Destination` (i.e, if you don't annotate any Composable with `@Destination`) then you should remove ksp from that module. Import only the `destinations:core` library.

Then you need to manually create your `NavGraphSpec`:

```kotlin
object DownloadNavGraph: NavGraphSpec {

    override val route = "download"

    override val startRoute = DownloadScreenDestination

    override val destinationsByRoute = listOf<DestinationSpec<*>>(
        DownloadScreenDestination,
        ErrorDialogDestination,
        CheckUpdateDialogDestination,
    ).associateBy { it.route }

}
```

Then pass this into your `DestinationsNavHost` call:

```kotlin
DestinationsNavHost(DownloadNavGraph)
```

Things to note:

1. `arg("compose-destinations.moduleName", "download")` this should be "core" for the core module.
2. `navGraph = "download"` is ignored when you set `arg("compose-destinations.mode", "destinations")` because your module will not produce any nav graph, it produces just a bunch of destinations. The nav graph has to be manually created in the module that calls `DestinationsNavHost` (like I shown above)
3. Does your ErrorDialog really make sense in the "download" nav graph? Because if it doesn't, then you can use the `arg("compose-destinations.mode", "navgraphs")` in your Download module, and then Download Module would create that navgraph for you. Of course back in the app module, you would need to still create some sort of "root" nav graph that contains both the ErrorDialog and generated DownloadModule as a `nestedNavGraphs`.
4. Check these two repositories:
https://github.com/raamcosta/CalorieTracker
https://github.com/raamcosta/tivi (unless you have Composable Destinations that belong to multiple nav graphs, you don't need to mind the `routedIn` and `withIn` usages here)

They have different approaches for multi module projects that may be helpful to you.

**Comment by raamcosta** [comment]
I'll close this, but please let me know if I can help you!

**Comment by S-H-Y-A** [comment]
I made custom a NavGraph while referring to the suggestion, but I received another error.

I can't share the project what I'm developing, so I'll share [Sample Project](https://github.com/S-H-Y-A/testComposeDestinationMultiModuleSample) which occur the same error.

```
2022-04-07 22:53:18.995 24018-24018/com.s_h_y_a.composeMultiModuleSample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.s_h_y_a.composeMultiModuleSample, PID: 24018
    java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/apk_download_dialog } cannot be found in the navigation graph NavGraph(0x78d845ec) route=home startDestination={Destination(0x81108029) route=home/home_screen}
        at androidx.navigation.NavController.navigate(NavController.kt:1660)
        at androidx.navigation.NavController.navigate(NavController.kt:1980)
        at androidx.navigation.NavController.navigate$default(NavController.kt:1975)
        at androidx.navigation.NavController.navigate(NavController.kt:1961)
        at com.ramcosta.composedestinations.navigation.DestinationsNavController.navigate(DestinationsNavController.kt:27)
        at com.ramcosta.composedestinations.navigation.DestinationsNavigator$DefaultImpls.navigate(DestinationsNavigator.kt:59)
        at com.ramcosta.composedestinations.navigation.DestinationsNavController.navigate(DestinationsNavController.kt:13)
        at com.ramcosta.composedestinations.navigation.DestinationsNavigator$DefaultImpls.navigate$default(DestinationsNavigator.kt:54)
        at com.s_h_y_a.composeMultiModuleSample.ComposableSingletons$MainActivityKt$lambda-1$1$1.navigate(MainActivity.kt:37)
        at com.s_h_y_a.composeMultiModuleSample.home.ui.HomeScreenKt$HomeScreen$1$1.invoke(HomeScreen.kt:18)
        at com.s_h_y_a.composeMultiModuleSample.home.ui.HomeScreenKt$HomeScreen$1$1.invoke(HomeScreen.kt:18)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:153)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:142)
        at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:223)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:557)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:452)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:465)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:310)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:179)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:98)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:80)
        at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1240)
        at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1190)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1129)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
2022-04-07 22:53:18.997 24018-24018/com.s_h_y_a.composeMultiModuleSample E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1892)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4195)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
        at android.view.View.dispatchPointerEvent(View.java:14799)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6364)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6160)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5638)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5695)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5661)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5826)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5669)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5883)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5642)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5695)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5661)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5669)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5642)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8587)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8538)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8507)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8710)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7835)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@e15b92c, androidx.compose.runtime.BroadcastFrameClock@1b36ff5, StandaloneCoroutine{Cancelling}@201818a, AndroidUiDispatcher@ad863fb]

```

How to solve this error?

**Comment by raamcosta** [comment]
In case you really needed to use `routedIn`, then when navigating you also need to specify which nav graph you want to navigate to (since that Destination can be in multiple NavGraphs). 
To do that you would have to use `within`:

```kotlin
navigator.navigate(YourDestinationWhichBelongsToMultipleNavGraphsDestination(navargs) within OneOfThoseNavGraphs)
```

Hope that is clear :) You can also read the documentation on `DynamicDestinationSpec` 🙂

**Comment by S-H-Y-A** [comment]
I appreciate for your kindness. All problems were solved. It works, now.
